import { logoutThroughAccount } from './navigation-helper';
import { test, expect, type Page } from '@playwright/test';
import { cardFixture, cardViewFixture, cardPurchase, cardAccount, bankAccount, expenseCategory, cardsSummaryFixture } from '../fixtures/cards';
import type { CardView, Purchase } from '../../src/features/finance/contracts.generated';
import { installmentPreview } from '../../src/features/finance/card-view';
const owner = '11111111-1111-4111-8111-111111111111', user = { id: owner, aud: 'authenticated', role: 'authenticated', email: 'test@example.test', created_at: '2026-01-01T00:00:00Z', app_metadata: {}, user_metadata: {} };
const token = [Buffer.from('{"alg":"ES256","kid":"synthetic"}').toString('base64url'), Buffer.from(JSON.stringify({ sub: owner, exp: Math.floor(Date.now() / 1000) + 3600 })).toString('base64url'), 'synthetic-signature'].join('.'), session = { access_token: token, refresh_token: 'synthetic-refresh', expires_in: 3600, token_type: 'bearer', user };
async function boundary(page: Page, configured = true) {
  const state = { view: configured ? cardViewFixture() : null as CardView | null, purchases: configured ? [structuredClone(cardPurchase)] : [] as Purchase[], writes: [] as { path: string; body: Record<string, unknown> }[], fail: false };
  const headers = { 'access-control-allow-origin': 'http://localhost:3103', 'access-control-allow-headers': '*', 'access-control-allow-methods': 'GET,POST,PATCH,OPTIONS' };
  await page.route('**/auth/v1/**', r => r.request().method() === 'OPTIONS' ? r.fulfill({ status: 204, headers }) : r.fulfill({ headers, json: new URL(r.request().url()).pathname.endsWith('/token') ? session : user }));
  await page.route('**/api/v1/**', async r => {
    const request = r.request(), url = new URL(request.url()), path = url.pathname, reply = (json: unknown, status = 200) => r.fulfill({ headers, json, status });
    if (request.method() === 'OPTIONS') return r.fulfill({ status: 204, headers });
    expect(request.headers().authorization).toBe('Bearer ' + token);
    if (path.endsWith('/me')) return reply({ identity: { authUserId: owner }, profile: { id: owner, displayName: 'Conta Teste', locale: 'pt-BR', timezone: 'America/Sao_Paulo', createdAt: user.created_at, updatedAt: user.created_at } });
    expect(path).toMatch(/^\/api\/v1\/finance\/(cards|accounts|categories)/);
    if (request.method() === 'GET') {
      if (state.fail && path.endsWith('/cards')) return reply({}, 503);
      if (path.endsWith('/accounts')) return reply([bankAccount, ...(state.view ? [cardAccount] : [])]);
      if (path.endsWith('/categories')) return reply([expenseCategory]);
      if (path.endsWith('/summary')) return reply(state.view ? cardsSummaryFixture : { ...cardsSummaryFixture, currencies: [] });
      if (path.endsWith('/purchases')) return reply({ items: state.purchases, nextCursor: null });
      if (path.endsWith('/cards')) return reply(state.view ? [state.view.card] : []);
      return reply(state.view);
    }
    const body = request.postDataJSON() as Record<string, unknown>;
    for (const field of ['auth_user_id', 'ownerId', 'pan', 'cvv', 'password']) expect(body).not.toHaveProperty(field);
    state.writes.push({ path, body });
    if (path.endsWith('/cards')) { state.view = cardViewFixture({ card: { ...cardFixture, displayName: String(body.displayName), last4: body.last4 as string | null }, invoices: [], realBalanceMinor: '0', recognizedLiabilityMinor: '0', futureInstallmentsMinor: '0', totalCommittedMinor: '0', estimatedUsedLimitMinor: '0', estimatedAvailableLimitMinor: '500000' }); return reply(state.view.card, 201); }
    if (path.endsWith('/archive')) { state.view!.card = { ...state.view!.card, status: 'ARCHIVED', archivedAt: '2026-10-05T12:00:00Z' }; return reply(state.view!.card); }
    if (path.endsWith('/billing-rules')) { const last = state.view!.rules.at(-1)!; last.effectiveTo = String(body.effectiveFrom); const next = { ...last, id: crypto.randomUUID(), effectiveFrom: String(body.effectiveFrom), effectiveTo: null, closingDay: Number(body.closingDay), dueDay: Number(body.dueDay) }; state.view!.rules.push(next); return reply(next, 201); }
    if (path.endsWith('/cancel')) { const p = state.purchases.find(p => path.includes(p.id))!; p.status = 'CANCELLED'; p.cancelledAt = '2026-10-05T12:00:00Z'; return reply(p); }
    if (path.endsWith('/payments')) { state.view!.realBalanceMinor = '0'; state.view!.recognizedLiabilityMinor = '0'; state.view!.invoices[0] = { ...state.view!.invoices[0]!, status: 'PAID', outstandingMinor: '0', paymentsAppliedMinor: String(body.amountMinor) }; return reply({ id: crypto.randomUUID(), ...body, destinationAccountId: cardAccount.id, currency: 'BRL', description: 'Payment', isCancelled: false, createdAt: '2026-10-05T12:00:00Z', updatedAt: '2026-10-05T12:00:00Z' }, 201); }
    const amount = String(body.totalAmountMinor), count = Number(body.installmentCount), currency = state.view!.card.currency;
    const raw = currency === 'BRL' ? String(BigInt(amount) / 100n) + '.' + String(BigInt(amount) % 100n).padStart(2, '0') : amount;
    const preview = installmentPreview(raw, currency, count, String(body.purchaseDate), state.view!.rules);
    const p: Purchase = { ...cardPurchase, ...body, id: crypto.randomUUID(), cardId: state.view!.card.id, currency, description: String(body.description), totalAmountMinor: amount, installmentCount: count, idempotencyKey: String(body.idempotencyKey), installments: preview.map(i => ({ ...i, id: crypto.randomUUID(), transactionId: crypto.randomUUID(), closingDate: i.closingDate!, dueDate: i.dueDate!, billingRuleId: state.view!.rules[0]!.id })) };
    state.purchases.unshift(p); return reply(p, 201);
  });
  return state;
}
async function login(page: Page) { await page.goto('/login'); await page.getByLabel('E-mail').fill('test@example.test'); await page.getByLabel('Senha', { exact: true }).fill('synthetic-password'); await page.getByRole('button', { name: 'Entrar na minha conta' }).click(); await expect(page.getByRole('heading', { name: 'Bom ter você aqui, Conta Teste.' })).toBeVisible(); await page.goto('/finance/cards'); await expect(page.getByRole('heading', { name: 'Cartões', exact: true })).toBeVisible(); }
async function detail(page: Page) { await page.goto('/finance/cards/' + cardFixture.id); await expect(page.getByRole('heading', { name: 'Saldo real e compromissos' })).toBeVisible(); }
test('create card, exact installments preview, single write and reload history', async ({ page }) => {
  const state = await boundary(page, false); await login(page); await page.getByRole('button', { name: 'Novo cartão', exact: true }).click(); await page.getByLabel('Nome do cartão', { exact: true }).fill('Cartão teste'); await page.getByLabel('Limite do cartão (opcional)').fill('5000'); await page.getByLabel('Últimos 4 dígitos (opcional)').fill('1234'); await page.getByRole('button', { name: 'Salvar cartão' }).click(); await expect(page.getByRole('heading', { name: 'Cartão teste · BRL' })).toBeVisible();
  await detail(page); await page.getByRole('button', { name: 'Nova compra', exact: true }).click(); await page.getByLabel('Descrição da compra').fill('Compra parcelada'); await page.getByLabel('Categoria de despesa').selectOption(expenseCategory.id); await page.getByLabel('Valor total (BRL)').fill('1000'); await page.getByLabel('Quantidade de parcelas').fill('3'); await expect(page.getByText(/3\/3.*333,34/)).toBeVisible(); await page.getByRole('button', { name: 'Registrar compra' }).dblclick(); await expect.poll(() => state.writes.length).toBe(2); expect(state.writes[1]?.body).toMatchObject({ totalAmountMinor: '100000', installmentCount: 3 }); await page.reload(); await expect(page.getByRole('heading', { name: 'Compra parcelada', exact: true })).toBeVisible(); expect(state.purchases[0]?.installments.map(i => i.amountMinor)).toEqual(['33333', '33333', '33334']);
});
test('payment uses transfer endpoint, invoice paid, no expense call', async ({ page }) => { const state = await boundary(page); await login(page); await detail(page); await page.getByRole('button', { name: 'Pagar fatura', exact: true }).click(); await expect(page.getByText(/Pagamento será registrado como transferência/)).toBeVisible(); await page.getByLabel('Conta de origem').selectOption(bankAccount.id); await page.getByRole('button', { name: 'Registrar pagamento' }).click(); await expect(page.getByRole('heading', { name: 'Fatura · 2026-10-10 · Paga' })).toBeVisible(); expect(state.writes).toHaveLength(1); expect(state.writes[0]?.path).toMatch(/\/cards\/.*\/payments$/); expect(state.writes[0]?.body).not.toHaveProperty('type'); expect(state.view?.invoices[0]?.postedChargesMinor).toBe('33333'); });
test('future billing version, correction, terminal archive preserves future and payment access', async ({ page }) => { const state = await boundary(page); await login(page); await detail(page); await page.getByRole('button', { name: 'Nova regra de ciclo' }).click(); await page.getByLabel('Vigência da nova regra').fill('2026-11-01'); await page.getByLabel('Novo dia de fechamento').fill('12'); await page.getByLabel('Novo dia de vencimento').fill('20'); await page.getByRole('button', { name: 'Salvar nova regra' }).click(); expect(state.view?.rules[0]?.closingDay).toBe(10); await page.getByRole('button', { name: 'Corrigir/cancelar — Parcelado teste' }).click(); await page.getByRole('button', { name: 'Confirmar correção', exact: true }).click(); await expect(page.getByText(/CANCELLED — correção/)).toBeVisible(); await page.getByRole('button', { name: 'Arquivar cartão', exact: true }).click(); await page.getByRole('button', { name: 'Confirmar arquivamento', exact: true }).click(); await expect(page.getByRole('button', { name: 'Nova compra', exact: true })).toBeDisabled(); await expect(page.getByRole('button', { name: 'Pagar fatura', exact: true })).toBeEnabled(); await expect(page.getByRole('heading', { name: 'Fatura · 2026-11-10 · Próxima' })).toBeVisible(); await page.reload(); await expect(page.getByText('BRL · Arquivado — histórico e parcelas preservados')).toBeVisible(); });
test('desktop/mobile/tablet/keyboard and input layout stability', async ({ page }, info) => {
  await boundary(page); await login(page); await detail(page); await page.getByRole('button', { name: 'Nova compra', exact: true }).focus(); await page.keyboard.press('Enter'); await expect(page.getByRole('heading', { name: 'Nova compra no cartão' })).toBeVisible(); const total = page.getByLabel('Valor total (BRL)'), submit = page.getByRole('button', { name: 'Registrar compra' }); await total.scrollIntoViewIfNeeded(); const yBefore = (await submit.boundingBox())!.y; await total.fill('1000'); await page.getByLabel('Quantidade de parcelas').fill('60'); const yAfter = (await submit.boundingBox())!.y; expect(Math.abs(yAfter - yBefore)).toBeLessThan(2); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.screenshot({ path: '.harness/tmp/cards-' + info.project.name + '.png', fullPage: true }); await page.setViewportSize({ width: 820, height: 1180 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.screenshot({ path: '.harness/tmp/cards-tablet-' + info.project.name + '.png', fullPage: true });
});
test('error retry and logout protect cards routes', async ({ page }) => { const state = await boundary(page); await login(page); state.fail = true; await page.reload(); await expect(page.getByText('Não foi possível carregar os cartões.', { exact: true })).toBeVisible(); state.fail = false; await page.getByRole('button', { name: 'Tentar novamente', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Cartão teste · BRL' })).toBeVisible(); await logoutThroughAccount(page); await page.goto('/finance/cards'); await expect(page).toHaveURL(/\/login$/); });
