import { logoutThroughAccount } from './navigation-helper';
import { test,expect,type Page } from '@playwright/test';
import { debtFixture,debtViewFixture,debtPaymentFixture,debtSummaryFixture,debtSimulationFixture } from '../fixtures/debts';
import { bankAccount,expenseCategory } from '../fixtures/cards';
import type { DebtPayment,DebtView } from '../../src/features/finance/contracts.generated';
const owner='11111111-1111-4111-8111-111111111111',user={id:owner,aud:'authenticated',role:'authenticated',email:'test@example.test',created_at:'2026-01-01T00:00:00Z',app_metadata:{},user_metadata:{}};
const token=[Buffer.from('{"alg":"ES256","kid":"synthetic"}').toString('base64url'),Buffer.from(JSON.stringify({sub:owner,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'synthetic-signature'].join('.'),session={access_token:token,refresh_token:'synthetic-refresh',expires_in:3600,token_type:'bearer',user};
async function boundary(page:Page,configured=true){const state={view:configured?debtViewFixture():null as DebtView|null,payments:[] as DebtPayment[],writes:[] as {path:string;body:Record<string,unknown>}[],fail:false,paymentFail:false};const headers={'access-control-allow-origin':'http://localhost:3103','access-control-allow-headers':'*','access-control-allow-methods':'GET,POST,PATCH,OPTIONS'};
  await page.route('**/auth/v1/**',r=>r.request().method()==='OPTIONS'?r.fulfill({status:204,headers}):r.fulfill({headers,json:new URL(r.request().url()).pathname.endsWith('/token')?session:user}));
  await page.route('**/api/v1/**',async r=>{const request=r.request(),path=new URL(request.url()).pathname,reply=(json:unknown,status=200)=>r.fulfill({headers,json,status});if(request.method()==='OPTIONS')return r.fulfill({status:204,headers});expect(request.headers().authorization).toBe('Bearer '+token);if(path.endsWith('/me'))return reply({identity:{authUserId:owner},profile:{id:owner,displayName:'Conta Teste',locale:'pt-BR',timezone:'America/Sao_Paulo',createdAt:user.created_at,updatedAt:user.created_at}});
    expect(path).toMatch(/^\/api\/v1\/finance\/(debts|accounts|categories|net-worth)/);
    if(request.method()==='GET'){if(state.fail&&path.endsWith('/debts'))return reply({},503);if(path.endsWith('/accounts'))return reply([bankAccount]);if(path.endsWith('/categories'))return reply([expenseCategory]);if(path.endsWith('/items'))return reply({items:[],nextCursor:null});if(path.endsWith('/summary'))return reply(state.view?debtSummaryFixture:{...debtSummaryFixture,currencies:[]});if(path.endsWith('/payments'))return reply({items:state.payments,nextCursor:null});if(path.endsWith('/debts'))return reply(state.view?[state.view.debt]:[]);return reply(state.view);}
    const body=request.postDataJSON() as Record<string,unknown>;for(const field of ['auth_user_id','ownerId','password'])expect(body).not.toHaveProperty(field);state.writes.push({path,body});
    if(path.endsWith('/debts')){state.view=debtViewFixture({debt:{...debtFixture,name:String(body.name)},outstandingPrincipalMinor:String(body.initialPrincipalMinor)});return reply(state.view.debt,201);}
    if(path.endsWith('/simulate'))return reply(debtSimulationFixture);
    if(path.endsWith('/terms')){const last=state.view!.terms.at(-1)!;last.effectiveTo=String(body.effectiveFrom);const next={...last,id:crypto.randomUUID(),rate:String(body.rate),ratePeriod:body.ratePeriod as typeof last.ratePeriod,minimumPaymentMinor:String(body.minimumPaymentMinor),dueDay:Number(body.dueDay),effectiveFrom:String(body.effectiveFrom),effectiveTo:null};state.view!.terms.push(next);return reply(next,201);}
    if(path.endsWith('/cancel')){const p=state.payments.find(p=>path.includes(p.id))!;p.status='CANCELLED';p.cancelledAt='2026-10-06T12:00:00Z';state.view!.outstandingPrincipalMinor='1000000';state.view!.debt={...state.view!.debt,status:'ACTIVE',paidOffAt:null};return reply(p);}
    if(path.endsWith('/archive')){state.view!.debt={...state.view!.debt,status:'ARCHIVED',archivedAt:'2026-10-06T12:00:00Z'};return reply(state.view!.debt);}
    if(path.endsWith('/payments')){if(state.paymentFail)return reply({error:{code:'CONFLICT',message:'Resource conflict.',requestId:'test'}},409);const remaining=String(BigInt(state.view!.outstandingPrincipalMinor)-BigInt(String(body.principalAmountMinor))),total=String(BigInt(String(body.principalAmountMinor))+BigInt(String(body.interestAmountMinor))+BigInt(String(body.feeAmountMinor)));const p:DebtPayment={...debtPaymentFixture,...body,id:crypto.randomUUID(),principalAmountMinor:String(body.principalAmountMinor),interestAmountMinor:String(body.interestAmountMinor),feeAmountMinor:String(body.feeAmountMinor),remainingPrincipalMinor:remaining,totalAmountMinor:total,paidAt:String(body.paidAt),idempotencyKey:String(body.idempotencyKey),interestCategoryId:body.interestCategoryId as string??null,feeCategoryId:body.feeCategoryId as string??null,transferId:body.principalAmountMinor==='0'?null:debtPaymentFixture.transferId,interestTransactionId:body.interestAmountMinor==='0'?null:debtPaymentFixture.interestTransactionId,feeTransactionId:body.feeAmountMinor==='0'?null:debtPaymentFixture.feeTransactionId};state.payments.unshift(p);state.view!.outstandingPrincipalMinor=remaining;state.view!.principalPaidMinor=p.principalAmountMinor;state.view!.interestPaidMinor=p.interestAmountMinor;state.view!.feesPaidMinor=p.feeAmountMinor;if(remaining==='0')state.view!.debt={...state.view!.debt,status:'PAID_OFF',paidOffAt:p.paidAt};return reply(p,201);}
    state.view!.debt={...state.view!.debt,name:String(body.name),lender:body.lender as string|null};return reply(state.view!.debt);
  });return state;
}
async function login(page:Page){await page.goto('/login');await page.getByLabel('E-mail').fill('test@example.test');await page.getByLabel('Senha',{exact:true}).fill('synthetic-password');await page.getByRole('button',{name:'Entrar na minha conta'}).click();await expect(page.getByRole('heading',{name:'Início'})).toBeVisible(); await expect(page.locator('#main .ui-page-header')).toContainText('Conta Teste');await page.goto('/finance/debts');await expect(page.getByRole('heading',{name:'Dívidas',exact:true})).toBeVisible();}
async function detail(page:Page){await page.goto('/finance/debts/'+debtFixture.id);await expect(page.getByRole('heading',{name:'Saldo real e pagamentos'})).toBeVisible();}
async function draft(page:Page){await page.getByRole('button',{name:'Registrar pagamento real',exact:true}).click();await page.getByLabel('Conta de origem').selectOption(bankAccount.id);await page.getByLabel('Principal pago (BRL)').fill('400');await page.getByLabel('Juros pagos (BRL)').fill('90');await page.getByLabel('Tarifas pagas (BRL)').fill('10');}
test('create positive principal and annual rate fraction, reload persisted record',async({page})=>{const state=await boundary(page,false);await login(page);await page.getByRole('button',{name:'Nova dívida',exact:true}).click();await page.getByLabel('Nome da dívida').fill('Dívida teste');await page.getByLabel('Principal atual (valor positivo)').fill('10000');await page.getByRole('button',{name:'Salvar dívida'}).click();await expect(page.getByRole('heading',{name:'Dívida teste · BRL'})).toBeVisible();expect(state.writes[0]!.body).toMatchObject({initialPrincipalMinor:'1000000',rate:'0.12',ratePeriod:'EFFECTIVE_ANNUAL',minimumPaymentMinor:'50000'});await page.reload();await expect(page.getByRole('heading',{name:'Dívida teste · BRL'})).toBeVisible();});
test('real payment previews exact split, single command and history survives reload',async({page})=>{const state=await boundary(page);await login(page);await detail(page);await draft(page);await expect(page.getByText(/Total debitado:.*500,00/)).toBeVisible();await expect(page.getByText(/Principal restante:.*9.600,00/)).toBeVisible();await page.getByRole('button',{name:'Registrar pagamento',exact:true}).dblclick();await expect.poll(()=>state.writes.length).toBe(1);expect(state.writes[0]!.body).toMatchObject({principalAmountMinor:'40000',interestAmountMinor:'9000',feeAmountMinor:'1000'});await expect(page.getByRole('heading',{name:'Registrar pagamento real',exact:true})).toBeHidden();await page.reload();await expect(page.locator('section').filter({has:page.getByRole('heading',{name:'Histórico de pagamentos reais',exact:true})}).getByText(/Total.*500,00.*Principal.*400,00.*Juros.*90,00.*Tarifas.*10,00/)).toBeVisible();expect(state.writes[0]!.path).toMatch(/debts\/.*\/payments$/);});
test('comparison is server-derived read-only with three strategies and savings',async({page})=>{const state=await boundary(page);await login(page);await page.getByRole('checkbox',{name:'Dívida teste'}).check();await page.getByRole('button',{name:'Comparar estratégias'}).click();await expect(page.getByRole('heading',{name:'Avalanche — maior taxa mensal'})).toBeVisible();await expect(page.getByRole('heading',{name:'Snowball — menor principal'})).toBeVisible();await expect(page.getByText('Economia estimada vs. mínimos')).toHaveCount(3);expect(state.writes).toHaveLength(1);expect(state.writes[0]!.path).toMatch(/debts\/simulate$/);});
test('future terms preserve history, payoff disables payment, correction reactivates and archive is terminal',async({page})=>{const state=await boundary(page);await login(page);await detail(page);await page.getByRole('button',{name:'Nova versão dos termos',exact:true}).click();await page.getByLabel('Vigência da nova taxa', { exact: true }).fill('2026-11-01');await page.getByLabel('Taxa efetiva (%)').fill('1.2');await page.getByLabel('Período da taxa').selectOption('EFFECTIVE_MONTHLY');await page.getByRole('button',{name:'Salvar nova versão'}).click();await expect(page.getByRole('heading',{name:'Nova versão dos termos',exact:true})).toBeHidden();expect(state.view!.terms[0]!.rate).toBe('0.12');expect(state.view!.terms[1]!.rate).toBe('0.012');await draft(page);await page.getByLabel('Principal pago (BRL)').fill('10000');await page.getByRole('button',{name:'Registrar pagamento',exact:true}).click();await expect(page.getByRole('heading',{name:'Registrar pagamento real',exact:true})).toBeHidden();await expect(page.getByRole('button',{name:'Registrar pagamento real',exact:true})).toBeDisabled();await page.getByRole('button',{name:/Corrigir pagamento/}).click();await page.getByRole('button',{name: 'Confirmar correção', exact: true }).click();await expect(page.getByRole('alertdialog',{name:'Confirmar correção de pagamento'})).toBeHidden();await expect(page.getByRole('button',{name:'Registrar pagamento real',exact:true})).toBeEnabled();await draft(page);await page.getByLabel('Principal pago (BRL)').fill('10000');await page.getByRole('button',{name:'Registrar pagamento',exact:true}).click();await expect(page.getByRole('heading',{name:'Registrar pagamento real',exact:true})).toBeHidden();await page.getByRole('button',{name:'Arquivar dívida quitada'}).click();await page.getByRole('button',{name: 'Confirmar arquivamento', exact: true }).click();await expect(page.getByRole('alertdialog',{name:'Arquivar dívida'})).toBeHidden();await page.reload();await expect(page.getByText(/Arquivada.*BRL/)).toBeVisible();await expect(page.getByRole('button',{name:'Registrar pagamento real',exact:true})).toBeDisabled();});
test('desktop/mobile/tablet keyboard, payment form has stable preview and no horizontal overflow',async({page},info)=>{await boundary(page);await login(page);await detail(page);await page.getByRole('button',{name:'Registrar pagamento real',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Registrar pagamento real',exact:true})).toBeVisible();const submit=page.getByRole('button',{name:'Registrar pagamento',exact:true});await submit.scrollIntoViewIfNeeded();const before=await submit.evaluate(el=>el.getBoundingClientRect().top+scrollY);await page.getByLabel('Principal pago (BRL)').fill('400');await page.getByLabel('Juros pagos (BRL)').fill('90');const after=await submit.evaluate(el=>el.getBoundingClientRect().top+scrollY);expect(Math.abs(after-before)).toBeLessThan(2);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.harness/tmp/debts-'+info.project.name+'.png',fullPage:true});await page.setViewportSize({width:820,height:1180});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.harness/tmp/debts-tablet-'+info.project.name+'.png',fullPage:true});});
test('uncertain retry retains key, error recovery and logout protect private routes',async({page})=>{const state=await boundary(page);await login(page);await detail(page);state.paymentFail=true;await draft(page);await page.getByRole('button',{name:'Registrar pagamento',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();state.paymentFail=false;await page.getByRole('button',{name:'Registrar pagamento',exact:true}).click();await expect.poll(()=>state.writes.length).toBe(2);expect(state.writes[0]!.body).toEqual(state.writes[1]!.body);await logoutThroughAccount(page);await page.goto('/finance/debts');await expect(page).toHaveURL(/\/login$/);});
