import { logoutThroughAccount } from './navigation-helper';
import { test,expect,type Page } from '@playwright/test';
import { netWorthSummary,netWorthHistory,netWorthItem } from '../fixtures/net-worth';
import type { NetWorthItem } from '../../src/features/finance/contracts.generated';
const owner='11111111-1111-4111-8111-111111111111',user={id:owner,aud:'authenticated',role:'authenticated',email:'test@example.test',created_at:'2026-01-01T00:00:00Z',app_metadata:{},user_metadata:{}};
const token=[Buffer.from('{"alg":"ES256","kid":"synthetic"}').toString('base64url'),Buffer.from(JSON.stringify({sub:owner,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'synthetic-signature'].join('.');
const session={access_token:token,refresh_token:'synthetic-refresh',expires_in:3600,token_type:'bearer',user};
async function boundary(page:Page){const state={row:null as NetWorthItem|null,writes:[] as {path:string;body:Record<string,unknown>}[],fail:false};const headers={'access-control-allow-origin':'http://localhost:3103','access-control-allow-headers':'*','access-control-allow-methods':'GET,POST,PATCH,OPTIONS'};
 await page.route('**/auth/v1/**',r=>r.request().method()==='OPTIONS'?r.fulfill({status:204,headers}):r.fulfill({headers,json:new URL(r.request().url()).pathname.endsWith('/token')?session:user}));
 await page.route('**/api/v1/**',async r=>{const req=r.request(),url=new URL(req.url()),path=url.pathname,method=req.method();if(method==='OPTIONS')return r.fulfill({status:204,headers});expect(req.headers().authorization).toBe('Bearer '+token);const reply=(json:unknown,status=200)=>r.fulfill({headers,json,status});if(path.endsWith('/me'))return reply({identity:{authUserId:owner},profile:{id:owner,displayName:'Conta Teste',locale:'pt-BR',timezone:'America/Sao_Paulo',createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'}});expect(path).toMatch(/^\/api\/v1\/finance\/net-worth/);
 if(method==='GET'){if(state.fail)return reply({},503);if(path.endsWith('/history'))return reply({...netWorthHistory,currency:url.searchParams.get('currency'),points:netWorthHistory.points.map(p=>({...p,currency:url.searchParams.get('currency')}))});if(path.endsWith('/valuations'))return reply({items:state.row?[state.row.latestValuation]:[],nextCursor:null});if(path.endsWith('/items'))return reply({items:state.row&&state.row.currency===url.searchParams.get('currency')&&state.row.status===url.searchParams.get('status')?[state.row]:[],nextCursor:null});return reply(netWorthSummary);}
 const body=req.postDataJSON() as Record<string,unknown>;expect(body).not.toHaveProperty('auth_user_id');expect(body).not.toHaveProperty('owner');state.writes.push({path,body});if(path.endsWith('/items')){state.row=netWorthItem({name:body.name as string,description:body.description as string|null,kind:body.kind as NetWorthItem['kind'],category:body.category as NetWorthItem['category'],currency:body.currency as NetWorthItem['currency']});return reply(state.row,201);}if(!state.row)return reply({},404);if(method==='PATCH'){expect(body).not.toHaveProperty('currency');expect(body).not.toHaveProperty('kind');Object.assign(state.row,body);}else if(path.endsWith('/archive'))Object.assign(state.row,{status:'ARCHIVED',archivedAt:'2026-10-05T12:00:00Z'});else if(path.endsWith('/valuations')){state.row.latestValuation={...state.row.latestValuation!,...body};return reply(state.row.latestValuation,201);}return reply(state.row);
 });return state;}
async function login(page:Page){await page.goto('/login');await page.getByLabel('E-mail').fill('test@example.test');await page.getByLabel('Senha',{exact:true}).fill('synthetic-password');await page.getByRole('button',{name:'Entrar na minha conta'}).click();await expect(page.getByRole('heading',{name:'Início'})).toBeVisible(); await expect(page.locator('#main .ui-page-header')).toContainText('Conta Teste');await page.goto('/finance/net-worth');await expect(page.getByRole('heading',{name:'Composição — BRL'})).toBeVisible();}
test('create → reload → metadata → zero valuation → history → archive never writes ledger',async({page})=>{const state=await boundary(page);await login(page);await page.getByRole('button',{name:'Novo item',exact:true}).click();await page.getByLabel('Nome',{exact:true}).fill('Carro teste');await page.getByLabel('Valor em BRL').fill('10000');await page.getByRole('button',{name:'Cadastrar item'}).click();await expect(page.getByRole('heading',{name:'Carro teste'})).toBeVisible();expect(state.writes[0]?.body.initialValueMinor).toBe('1000000');await page.reload();await page.getByRole('button',{name:'Editar dados'}).click();await expect(page.getByLabel('Tipo do item')).toBeDisabled();await page.getByLabel('Nome',{exact:true}).fill('Carro atualizado');await page.getByRole('button',{name:'Salvar dados'}).click();await expect(page.getByRole('heading',{name:'Carro atualizado'})).toBeVisible();await page.getByRole('button',{name:'Nova avaliação',exact:true}).click();await page.getByLabel('Valor em BRL').fill('0');await page.getByRole('button',{name:'Salvar avaliação'}).click();await expect.poll(()=>state.row?.latestValuation?.valueMinor).toBe('0');await page.getByRole('button',{name:'Ver histórico'}).click();await expect(page.getByRole('heading',{name:'Histórico de avaliações — Carro atualizado'})).toBeVisible();await page.getByRole('button',{name:'Fechar histórico'}).click();await page.getByRole('button',{name:'Arquivar',exact:true}).click();await page.getByRole('button',{name:'Confirmar arquivamento'}).click();await page.getByLabel('Status dos itens').selectOption('ARCHIVED');await expect(page.getByRole('heading',{name:'Carro atualizado'})).toBeVisible();await expect(page.getByRole('button',{name:'Nova avaliação',exact:true})).toHaveCount(0);expect(state.writes).toHaveLength(4);expect(state.writes.every(w=>w.path.includes('/net-worth/items'))).toBe(true);});
test('desktop/mobile/tablet show separate currencies, accessible chart, retry and keyboard form',async({page},info)=>{const state=await boundary(page);await login(page);await expect(page.getByRole('table')).toBeVisible();await expect(page.getByText('Conta principal · Conta inativa')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.harness/tmp/net-worth-'+info.project.name+'.png',fullPage:true});await page.getByLabel('Moeda do patrimônio').selectOption('USD');await expect(page.getByRole('heading',{name:'Composição — USD'})).toBeVisible();await page.setViewportSize({width:820,height:1180});await page.getByRole('button',{name:'Novo item',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Novo item patrimonial'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.harness/tmp/net-worth-tablet-'+info.project.name+'.png',fullPage:true});await page.getByRole('button',{name:'Cancelar',exact:true}).click();state.fail=true;await page.reload();await expect(page.getByText('Não foi possível carregar o patrimônio.')).toBeVisible();state.fail=false;await page.getByRole('button',{name:'Tentar novamente',exact:true}).first().click();await expect(page.getByRole('heading',{name:'Composição — BRL'})).toBeVisible();await logoutThroughAccount(page);await page.goto('/finance/net-worth');await expect(page).toHaveURL(/\/login$/);});
