import { randomUUID } from 'node:crypto';
import { test,expect,type Page } from '@playwright/test';
import type { Recurrence } from '../../src/features/finance/contracts.generated';
import { accountFixture,categoryFixture,recurrenceFixture,entryFixture,calendarFixture,radarFixture } from '../fixtures/recurrences';
const owner='11111111-1111-4111-8111-111111111111',user={id:owner,aud:'authenticated',role:'authenticated',email:'test@example.test',created_at:'2026-01-01T00:00:00Z',app_metadata:{},user_metadata:{}};
const token=[Buffer.from('{"alg":"ES256","kid":"synthetic"}').toString('base64url'),Buffer.from(JSON.stringify({sub:owner,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'synthetic-signature'].join('.');
const session={access_token:token,refresh_token:'synthetic-refresh',expires_in:3600,token_type:'bearer',user};
// Canned server dates exercise rendering/navigation. The real anchored engine is tested in Back against PostgreSQL.
const projectedDates=['2026-10-31','2026-11-30','2026-12-31','2027-01-31'];
async function boundary(page:Page,initial:Recurrence[]=[],options={fail:false,inactive:false}){
  const state={rows:initial,writes:[] as {path:string;body:Record<string,unknown>}[],reads:[] as string[],fail:options.fail};
  const headers={'access-control-allow-origin':'http://localhost:3103','access-control-allow-headers':'*','access-control-allow-methods':'GET,POST,PATCH,OPTIONS'};
  await page.route('**/auth/v1/**',route=>route.request().method()==='OPTIONS'?route.fulfill({status:204,headers}):route.fulfill({status:200,headers,json:new URL(route.request().url()).pathname.endsWith('/token')?session:user}));
  await page.route('**/api/v1/**',async route=>{
    const req=route.request(),url=new URL(req.url()),method=req.method(),path=url.pathname;
    if(method==='OPTIONS')return route.fulfill({status:204,headers});expect(req.headers().authorization).toBe('Bearer '+token);
    const reply=(json:unknown,status=200)=>route.fulfill({headers,json,status});
    if(path.endsWith('/me'))return reply({identity:{authUserId:owner},profile:{id:owner,displayName:'Conta Teste',locale:'pt-BR',timezone:'America/Sao_Paulo',createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'}});
    if(path.endsWith('/accounts'))return reply([{...accountFixture,isActive:!options.inactive},{...accountFixture,id:'55555555-5555-4555-8555-555555555555',currency:'USD',name:'Conta USD'}]);
    if(path.endsWith('/categories'))return reply([{...categoryFixture,isActive:!options.inactive},{...categoryFixture,id:'66666666-6666-4666-8666-666666666666',name:'Salário',kind:'INCOME'}]);
    expect(path).toMatch(/^\/api\/v1\/finance\/(recurrences|calendar|subscriptions\/radar)/);
    if(method==='GET'){
      state.reads.push(path+url.search);if(state.fail)return reply({},503);
      const filtered=state.rows.filter(row=>['status','currency','transactionType','recurrenceKind','accountId','categoryId'].every(key=>!url.searchParams.get(key)||row[key as keyof Recurrence]===url.searchParams.get(key)));
      if(path.endsWith('/calendar')){const from=url.searchParams.get('from')!,to=url.searchParams.get('to')!;const entries=filtered.filter(r=>r.status==='ACTIVE').flatMap(r=>projectedDates.filter(date=>date>=from&&date<to).map(date=>entryFixture(r,date)));return reply(calendarFixture(entries,from,to));}
      if(path.endsWith('/radar')){const active=filtered.filter(r=>r.status==='ACTIVE'&&r.recurrenceKind==='SUBSCRIPTION');return reply(radarFixture(active,active.map(r=>entryFixture(r))));}
      return reply({items:filtered,nextCursor:null});
    }
    const body=req.postDataJSON() as Record<string,unknown>;expect(body).not.toHaveProperty('auth_user_id');expect(body).not.toHaveProperty('nextOccurrenceDate');expect(body).not.toHaveProperty('owner');state.writes.push({path,body});
    const id=path.split('/')[5],row=state.rows.find(r=>r.id===id);
    if(!id&&method==='POST'){const created=recurrenceFixture({...body,id:randomUUID()} as Partial<Recurrence>);state.rows.push(created);return reply(created,201);}
    if(!row)return reply({},404);
    if(method==='PATCH'){expect(body).not.toHaveProperty('currency');expect(body).not.toHaveProperty('transactionType');Object.assign(row,body);return reply(row);}
    expect(body).toEqual({});const action=path.split('/').at(-1);Object.assign(row,{status:action==='pause'?'PAUSED':action==='resume'?'ACTIVE':'ARCHIVED',nextOccurrenceDate:action==='resume'?'2026-10-31':null,archivedAt:action==='archive'?'2026-10-02T12:00:00Z':null});return reply(row);
  });return state;
}
async function login(page:Page,path='/finance/recurrences'){await page.goto('/login');await page.getByLabel('E-mail').fill('test@example.test');await page.getByLabel('Senha',{exact:true}).fill('synthetic-password');await page.getByRole('button',{name:'Entrar na minha conta'}).click();await expect(page.getByRole('heading',{name:'Bom ter você aqui, Conta Teste.'})).toBeVisible();await page.goto(path);}
test('create subscription → reload → edit → pause/resume → archive preserves rule and never posts ledger',async({page})=>{
  const state=await boundary(page);await login(page);await expect(page.getByRole('heading',{name:'Cadastre sua primeira recorrência'})).toBeVisible();await page.getByRole('button',{name:'Nova recorrência',exact:true}).click();await page.getByLabel('Nome',{exact:true}).fill('Assinatura teste');await page.getByRole('combobox',{name:'Classificação',exact:true}).selectOption('SUBSCRIPTION');await expect(page.getByRole('combobox',{name:'Tipo',exact:true})).toBeDisabled();await page.getByLabel('Valor em BRL').fill('100,00');await page.getByLabel('Data inicial').fill('2026-10-31');await page.getByLabel('Conta opcional').selectOption(accountFixture.id);await page.getByLabel('Categoria opcional').selectOption(categoryFixture.id);await page.getByRole('button',{name:'Cadastrar recorrência'}).click();await expect(page.getByText('Recorrência cadastrada.')).toBeVisible();expect(state.writes[0]?.body).toMatchObject({amountMinor:'10000',startDate:'2026-10-31',transactionType:'EXPENSE'});await page.reload();await expect(page.getByRole('heading',{name:'Assinatura teste',exact:true})).toBeVisible();await expect(page.getByText('1 cobrança prevista em 30 dias')).toBeVisible();
  await page.getByRole('button',{name:'Editar Assinatura teste'}).click();await expect(page.getByRole('combobox',{name:'Moeda',exact:true})).toBeDisabled();await expect(page.getByRole('combobox',{name:'Tipo',exact:true})).toBeDisabled();await page.getByLabel('Valor em BRL').fill('150');await page.getByRole('button',{name:'Salvar alterações'}).click();await expect(page.getByText('Recorrência atualizada.')).toBeVisible();await page.getByRole('button',{name:'Pausar',exact:true}).click();await expect(page.getByText('Nenhuma assinatura ativa.')).toBeVisible();await page.goto('/finance/calendar?month=2026-10');await expect(page.getByText('Nenhuma ocorrência prevista neste período.')).toBeVisible();await page.goto('/finance/recurrences');await page.getByRole('button',{name:'Retomar',exact:true}).click();await expect(page.getByText('1 cobrança prevista em 30 dias')).toBeVisible();await page.getByRole('button',{name:'Arquivar',exact:true}).click();expect(state.writes).toHaveLength(4);await expect(page.getByText(/não poderá ser retomada/)).toBeVisible();await page.getByRole('button',{name:'Confirmar arquivamento'}).click();await expect(page.getByRole('article').getByText('Arquivada',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Retomar',exact:true})).toHaveCount(0);await page.getByLabel('Status das recorrências').selectOption('ARCHIVED');await expect(page.getByRole('heading',{name:'Assinatura teste',exact:true})).toBeVisible();expect(state.rows).toHaveLength(1);expect(state.writes.every(w=>w.path.startsWith('/api/v1/finance/recurrences'))).toBe(true);
});
test('calendar displays anchored month-end dates supplied by server and separate income/expense/currency totals',async({page})=>{
  const rows=[recurrenceFixture(),recurrenceFixture({id:randomUUID(),name:'Receita teste',transactionType:'INCOME',recurrenceKind:'STANDARD',amountMinor:'50000'}),recurrenceFixture({id:randomUUID(),name:'Assinatura USD',currency:'USD',amountMinor:'3000'})];const state=await boundary(page,rows);await login(page,'/finance/calendar?month=2026-10');for(const date of ['31/10/2026','30/11/2026','31/12/2026','31/01/2027']){await expect(page.locator('time',{hasText:date})).toBeVisible();await expect(page.getByText('Líquido previsto',{exact:true})).toHaveCount(2);await expect(page.getByText(/não é saldo disponível/)).toBeVisible();if(date!=='31/01/2027')await page.getByRole('button',{name:'Próximo mês'}).click();}await page.getByLabel('Moeda do calendário').selectOption('USD');await expect(page.getByRole('heading',{name:'BRL',exact:true})).toHaveCount(0);await expect(page.getByRole('heading',{name:'USD',exact:true})).toBeVisible();await expect(page.getByText('Receita teste',{exact:true})).toHaveCount(0);expect(state.reads.some(u=>u.includes('from=2027-01-01')&&u.includes('to=2027-02-01'))).toBe(true);expect(state.writes).toHaveLength(0);
});
test('filters compose, and inactive existing associations remain visible and editable',async({page})=>{
  const row=recurrenceFixture({accountId:accountFixture.id,categoryId:categoryFixture.id,account:{id:accountFixture.id,name:accountFixture.name,isActive:false},category:{id:categoryFixture.id,name:categoryFixture.name,kind:'EXPENSE',isActive:false}});const state=await boundary(page,[row,recurrenceFixture({id:randomUUID(),name:'USD',currency:'USD'})],{fail:false,inactive:true});await login(page);await expect(page.getByText(/Conta: Conta BRL · inativa/)).toBeVisible();await page.getByRole('button',{name:'Editar '+row.name}).click();await expect(page.getByLabel('Conta opcional')).toHaveValue(accountFixture.id);await expect(page.getByLabel('Categoria opcional')).toHaveValue(categoryFixture.id);await page.getByLabel('Nome',{exact:true}).fill('Renomeada');await page.getByRole('button',{name:'Salvar alterações'}).click();await expect(page.getByRole('heading',{name:'Renomeada'})).toBeVisible();await page.getByLabel('Moeda das recorrências').selectOption('BRL');await page.getByLabel('Classificação das recorrências').selectOption('SUBSCRIPTION');await expect(page.getByRole('heading',{name:'USD',exact:true})).toHaveCount(0);await expect.poll(()=>state.reads.some(s=>s.includes('currency=BRL')&&s.includes('recurrenceKind=SUBSCRIPTION'))).toBe(true);await page.getByRole('button',{name:'Nova recorrência',exact:true}).click();await expect(page.getByLabel('Conta opcional').getByRole('option',{name:/Conta BRL/})).toHaveCount(0);await expect(page.getByLabel('Categoria opcional').getByRole('option',{name:/Serviços/})).toHaveCount(0);
});
test('form rejects zero, incompatible interval and reversed dates before writing',async({page})=>{const state=await boundary(page);await login(page);await page.getByRole('button',{name:'Nova recorrência',exact:true}).click();await page.getByLabel('Nome',{exact:true}).fill('Regra inválida');await page.getByLabel('Valor em BRL').fill('0');await page.getByLabel('Intervalo').fill('25');await page.getByLabel('Data inicial').fill('2026-10-31');await page.getByLabel('Data final opcional').fill('2026-10-01');await page.getByRole('button',{name:'Cadastrar recorrência'}).click();await expect(page.getByText('Use um intervalo de 1 a 24.')).toBeVisible();await expect(page.getByText(/data final deve ser válida/)).toBeVisible();expect(state.writes).toHaveLength(0);});
test('service errors and retry never invent projections',async({page})=>{const state=await boundary(page,[],{fail:true,inactive:false});await login(page);await expect(page.getByText('Não foi possível carregar suas recorrências.')).toBeVisible();await expect(page.getByText('Não foi possível carregar o radar de assinaturas.')).toBeVisible();state.fail=false;await page.getByRole('button',{name:'Tentar novamente recorrências'}).click();await expect(page.getByText('Cadastre sua primeira recorrência')).toBeVisible();await page.goto('/finance/calendar?month=2026-10');await expect(page.getByText('Nenhuma ocorrência prevista neste período.')).toBeVisible();await page.getByRole('button',{name:'Sair da conta'}).click();await page.goto('/finance/recurrences');await expect(page).toHaveURL(/\/login$/);});
test('desktop/mobile/tablet layouts and keyboard navigation keep agenda and forms usable',async({page},testInfo)=>{await boundary(page,[recurrenceFixture()]);await login(page);await expect(page.getByRole('heading',{name:'Assinatura teste',exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'.harness/tmp/recurrences-'+testInfo.project.name+'.png',fullPage:true});await page.getByRole('button',{name:'Nova recorrência',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByLabel('Nome',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'.harness/tmp/recurrence-form-'+testInfo.project.name+'.png',fullPage:true});await page.goto('/finance/calendar?month=2026-10');await expect(page.getByText('Assinatura teste',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'.harness/tmp/calendar-'+testInfo.project.name+'.png',fullPage:true});await page.setViewportSize({width:820,height:1180});await page.getByRole('button',{name:'Próximo mês'}).focus();await page.keyboard.press('Enter');await expect(page.locator('time',{hasText:'30/11/2026'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'.harness/tmp/calendar-tablet-'+testInfo.project.name+'.png',fullPage:true});});
