import { test,expect,type Page } from '@playwright/test';
import { safeSettings,safeView } from '../fixtures/safe-spend';
import { bankAccount,cardAccount } from '../fixtures/cards';
import type { SafeSpendSettings } from '../../src/features/finance/contracts.generated';
const owner='11111111-1111-4111-8111-111111111111',user={id:owner,aud:'authenticated',role:'authenticated',email:'test@example.test',created_at:'2026-01-01T00:00:00Z',app_metadata:{},user_metadata:{}};
const token=[Buffer.from('{"alg":"ES256","kid":"synthetic"}').toString('base64url'),Buffer.from(JSON.stringify({sub:owner,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'synthetic-signature'].join('.'),session={access_token:token,refresh_token:'synthetic-refresh',expires_in:3600,token_type:'bearer',user};
async function boundary(page:Page,configured=true){const state={settings:configured?{...safeSettings}:null as SafeSpendSettings|null,writes:[] as Record<string,unknown>[],fail:false,shortfall:false},headers={'access-control-allow-origin':'http://localhost:3103','access-control-allow-headers':'*','access-control-allow-methods':'GET,PUT,OPTIONS'};
  await page.route('**/auth/v1/**',r=>r.request().method()==='OPTIONS'?r.fulfill({status:204,headers}):r.fulfill({headers,json:new URL(r.request().url()).pathname.endsWith('/token')?session:user}));
  await page.route('**/api/v1/**',r=>{const req=r.request(),url=new URL(req.url()),p=url.pathname,reply=(json:unknown,status=200)=>r.fulfill({headers,json,status});if(req.method()==='OPTIONS')return r.fulfill({status:204,headers});if(p.endsWith('/me'))return reply({identity:{authUserId:owner},profile:{id:owner,displayName:'Conta Teste',locale:'pt-BR',timezone:'America/Sao_Paulo',createdAt:user.created_at,updatedAt:user.created_at}});expect(p).toMatch(/^\/api\/v1\/finance\/(accounts|safe-to-spend)/);if(p.endsWith('/accounts'))return reply([bankAccount,cardAccount]);if(req.method()==='PUT'){expect(p).toMatch(/safe-to-spend\/settings$/);const body=req.postDataJSON() as Record<string,unknown>;expect(body).not.toHaveProperty('ownerId');state.writes.push(body);state.settings={...safeSettings,...body};return reply(state.settings);}if(p.endsWith('/settings'))return reply(state.settings);if(state.fail)return reply({},503);return reply(state.shortfall?{...safeView,status:'OVERCOMMITTED',rawSafeToSpendMinor:'-50000',safeToSpendMinor:'0',shortfallMinor:'50000'}:safeView);});return state;
}
async function login(page:Page){await page.goto('/login');await page.getByLabel('E-mail').fill('test@example.test');await page.getByLabel('Senha',{exact:true}).fill('synthetic-password');await page.getByRole('button',{name:'Entrar na minha conta'}).click();await expect(page.getByRole('heading',{name:'Início'})).toBeVisible(); await expect(page.locator('#main .ui-page-header')).toContainText('Conta Teste');await page.goto('/finance/safe-to-spend');await expect(page.getByRole('heading',{name:'Quanto posso gastar com segurança?'})).toBeVisible();}
test('explicit onboarding, exact buffer, single settings command and reload persistence',async({page})=>{const s=await boundary(page,false);await login(page);await expect(page.getByTestId('safe-spend-headline')).toHaveCount(0);const box=page.getByRole('checkbox').first();await expect(box).not.toBeChecked();await box.check();await page.getByLabel('Quanto deseja manter intocado? (BRL)').fill('500');await page.getByRole('button',{name:'Salvar configuração'}).dblclick();await expect.poll(()=>s.writes.length).toBe(1);expect(s.writes[0]).toMatchObject({accountIds:[bankAccount.id],safetyBufferMinor:'50000'});await expect(page.getByTestId('safe-spend-headline')).toContainText('1.800,00');await page.reload();await expect(page.getByTestId('safe-spend-headline')).toContainText('1.800,00');});
test('read-only server breakdown, budget cap and confirmed/planned/projected labels',async({page})=>{const s=await boundary(page);await login(page);await expect(page.getByTestId('safe-spend-headline')).toContainText('1.800,00');await expect(page.getByRole('heading',{name:'Como o valor foi calculado'})).toBeVisible();await expect(page.getByRole('heading',{name:'Se as receitas previstas entrarem'})).toBeVisible();await expect(page.getByText(/Confirmado · Considerado/)).toBeVisible();expect(s.writes).toHaveLength(0);});
test('shortfall is zero headline with explicit gap; error/retry never shows partial values',async({page})=>{const s=await boundary(page);s.shortfall=true;await login(page);await expect(page.getByTestId('safe-spend-headline')).toContainText('0,00');await expect(page.getByText(/Faltam.*500,00/)).toBeVisible();s.fail=true;await page.getByRole('button',{name:'Atualizar cálculo'}).click();await expect(page.getByText(/Estimativa indisponível/)).toBeVisible();await expect(page.getByTestId('safe-spend-headline')).toHaveCount(0);s.fail=false;await page.getByRole('button',{name:'Tentar novamente'}).click();await expect(page.getByTestId('safe-spend-headline')).toContainText('0,00');expect(s.writes).toHaveLength(0);});
test('tablet keyboard and stable form layout; no selection default or currency mixing',async({page},info)=>{test.skip(info.project.name!=='desktop','Tablet viewport covered once.');await page.setViewportSize({width:820,height:1180});await boundary(page,false);await login(page);const box=page.getByRole('checkbox').first();await box.focus();await page.keyboard.press('Space');await expect(box).toBeChecked();const button=page.getByRole('button',{name:'Salvar configuração'}),before=await button.boundingBox();await page.getByLabel('Quanto deseja manter intocado? (BRL)').fill('500');const after=await button.boundingBox();expect(Math.abs(after!.y-before!.y)).toBeLessThan(1);await expect(page.getByRole('checkbox',{name:/Conta credit/})).toHaveCount(0);await page.getByLabel('Moeda do planejamento').selectOption('USD');await expect(page.getByText(/Nenhuma conta ativa elegível nesta moeda/)).toBeVisible();await expect(button).toBeDisabled();});
