import { test,expect,type Page } from '@playwright/test';
import { yieldAccount,yieldProfile,yieldEstimate,yieldBenchmarks,yieldSummary } from '../fixtures/yield';
import type { YieldProfile,YieldRuleInput,YieldRule } from '../../src/features/finance/contracts.generated';
const owner='11111111-1111-4111-8111-111111111111',user={id:owner,aud:'authenticated',role:'authenticated',email:'test@example.test',created_at:'2026-01-01T00:00:00Z',app_metadata:{},user_metadata:{}};
const token=[Buffer.from('{"alg":"ES256","kid":"synthetic"}').toString('base64url'),Buffer.from(JSON.stringify({sub:owner,exp:Math.floor(Date.now()/1000)+3600})).toString('base64url'),'synthetic-signature'].join('.'),session={access_token:token,refresh_token:'synthetic-refresh',expires_in:3600,token_type:'bearer',user};
async function boundary(page:Page,configured=false){const state={row:configured?yieldProfile():null as YieldProfile|null,writes:[] as {path:string;body:Record<string,unknown>}[],fail:false,reads:[] as string[]};const headers={'access-control-allow-origin':'http://localhost:3103','access-control-allow-headers':'*','access-control-allow-methods':'GET,POST,OPTIONS'};
 await page.route('**/auth/v1/**',r=>r.request().method()==='OPTIONS'?r.fulfill({status:204,headers}):r.fulfill({headers,json:new URL(r.request().url()).pathname.endsWith('/token')?session:user}));
 await page.route('**/api/v1/**',async r=>{const req=r.request(),url=new URL(req.url()),path=url.pathname;if(req.method()==='OPTIONS')return r.fulfill({status:204,headers});expect(req.headers().authorization).toBe('Bearer '+token);const reply=(json:unknown,status=200)=>r.fulfill({headers,json,status});if(path.endsWith('/me'))return reply({identity:{authUserId:owner},profile:{id:owner,displayName:'Conta Teste',locale:'pt-BR',timezone:'America/Sao_Paulo',createdAt:user.created_at,updatedAt:user.created_at}});expect(path).toMatch(/^\/api\/v1\/finance\/(yield|accounts)/);
 if(req.method()==='GET'){state.reads.push(path+url.search);if(state.fail&&path.endsWith('/profiles'))return reply({},503);if(path.endsWith('/accounts'))return reply([yieldAccount]);if(path.endsWith('/profiles'))return reply(state.row?[state.row]:[]);if(path.endsWith('/benchmarks'))return reply(yieldBenchmarks);if(path.endsWith('/summary'))return reply(yieldSummary);return reply({...yieldEstimate,nextAnniversary:state.row?.rules.at(-1)?.ruleType==='SAVINGS_BR'?'2026-11-01':null});}
 const body=req.postDataJSON() as Record<string,unknown>;expect(body).not.toHaveProperty('auth_user_id');expect(body).not.toHaveProperty('ownerId');state.writes.push({path,body});if(path.endsWith('/comparison'))return reply({cdi:yieldEstimate,savings:yieldEstimate,fixed:yieldEstimate});if(path.endsWith('/archive')){state.row!.status='ARCHIVED';return reply(state.row);}
 const input=body as YieldRuleInput,newRule:YieldRule={...input,id:crypto.randomUUID(),profileId:yieldProfile().id,effectiveTo:null,benchmark:input.benchmark??null,benchmarkPercentage:input.benchmarkPercentage??null,fixedRate:input.fixedRate??null,ratePeriod:input.ratePeriod??null,eligibilityDelayDays:input.eligibilityDelayDays??0,eligibleBalanceCapMinor:input.eligibleBalanceCapMinor??null,taxReferenceDate:input.taxReferenceDate??null,createdAt:user.created_at};if(path.endsWith('/versions')){state.row!.rules.at(-1)!.effectiveTo=input.effectiveFrom;state.row!.rules.push(newRule);}else state.row=yieldProfile({rules:[newRule]});return reply(state.row,201);
 });return state;}
async function login(page:Page){await page.goto('/login');await page.getByLabel('E-mail').fill('test@example.test');await page.getByLabel('Senha',{exact:true}).fill('synthetic-password');await page.getByRole('button',{name:'Entrar na minha conta'}).click();await expect(page.getByRole('heading',{name:'Bom ter você aqui, Conta Teste.'})).toBeVisible();await page.goto('/finance/yield');await expect(page.getByRole('heading',{name:'Rendimentos',exact:true})).toBeVisible();}
test('configure fixed, reload, future version CDI115%, historical rules and read-only comparison',async({page})=>{const state=await boundary(page);await login(page);await page.getByRole('button',{name:'Configurar rendimento'}).click();await page.getByLabel('Taxa efetiva (%)',{exact:true}).fill('10');await page.getByRole('button',{name:'Salvar rendimento'}).click();await expect(page.getByRole('heading',{name:'Conta rendimento · BRL'})).toBeVisible();expect(state.writes[0]?.body.fixedRate).toBe('0.1');await page.reload();await expect(page.getByRole('heading',{name:'Projeção — 30 dias'})).toBeVisible();await page.getByRole('button',{name:'Nova versão — Conta rendimento'}).click();await page.getByLabel('Tipo de rendimento').selectOption('CDI');await page.getByLabel('Percentual do benchmark (%)').fill('115');await page.getByLabel('Estimativa de impostos').selectOption('BR_FIXED_INCOME_STANDARD');await page.getByRole('button',{name:'Salvar nova versão'}).click();await expect.poll(()=>state.row?.rules.length).toBe(2);expect(state.row?.rules[0]?.fixedRate).toBe('0.1');expect(state.row?.rules[1]?.benchmarkPercentage).toBe('1.15');await page.getByText('Histórico de regras — Conta rendimento',{exact:true}).click();await expect(page.getByText('115% CDI',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Comparar rendimentos'}).click();await expect(page.getByRole('heading',{name:'100% CDI',exact:true})).toBeVisible();expect(state.writes).toHaveLength(3);expect(state.writes.every(w=>w.path.includes('/yield-profile')||w.path.endsWith('/yield/comparison'))).toBe(true);});
test('responsive desktop/mobile/tablet, benchmark states, horizons and keyboard form',async({page},info)=>{const state=await boundary(page,true);await login(page);await expect(page.getByRole('heading',{name:'CDI',exact:true})).toBeVisible();await expect(page.getByText('Usando o último dado disponível.',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'USD · 1 conta(s)'})).toBeVisible();await page.getByLabel('Prazo da projeção — Conta rendimento').selectOption('90');await expect(page.getByRole('heading',{name:'Projeção — 90 dias'})).toBeVisible();await page.getByLabel('Prazo da projeção — Conta rendimento').selectOption('365');await expect(page.getByRole('heading',{name:'Projeção — 365 dias'})).toBeVisible();await page.getByLabel('Prazo da projeção — Conta rendimento').selectOption('custom');await expect(page.getByLabel('Fim da projeção — Conta rendimento')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.harness/tmp/yield-'+info.project.name+'.png',fullPage:true});await page.setViewportSize({width:820,height:1180});await page.getByRole('button',{name:'Nova versão — Conta rendimento'}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Nova versão de rendimento'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'.harness/tmp/yield-tablet-'+info.project.name+'.png',fullPage:true});expect(state.writes).toHaveLength(0);});
test('savings explicit setup and anniversary, terminal archive keeps rule history',async({page})=>{const state=await boundary(page);await login(page);await page.getByRole('button',{name:'Configurar rendimento'}).click();await page.getByLabel('Tipo de rendimento').selectOption('SAVINGS_BR');await expect(page.getByText(/Usa o menor saldo real do período/)).toBeVisible();await expect(page.getByLabel('Taxa efetiva (%)')).toHaveCount(0);await page.getByRole('button',{name:'Salvar rendimento'}).click();await expect(page.getByRole('heading',{name:'Conta rendimento · BRL'})).toBeVisible();expect(state.row?.rules[0]?.taxTreatment).toBe('BR_SAVINGS_EXEMPT');await expect(page.getByText(/Próximo aniversário estimado/).first()).toBeVisible();await page.getByRole('button',{name:'Arquivar rendimento — Conta rendimento'}).click();await page.getByRole('button',{name:'Confirmar arquivamento'}).click();await expect(page.getByText('Projeções futuras desabilitadas; histórico preservado.')).toBeVisible();expect(state.row?.rules).toHaveLength(1);});
test('error/retry and logout protect yield data',async({page})=>{const state=await boundary(page,true);await login(page);state.fail=true;await page.reload();await expect(page.getByText('Não foi possível carregar as contas.')).toBeVisible();state.fail=false;await page.getByRole('button',{name:'Tentar novamente',exact:true}).click();await expect(page.getByRole('heading',{name:'Conta rendimento · BRL'})).toBeVisible();await page.getByRole('button',{name:'Sair da conta'}).click();await page.goto('/finance/yield');await expect(page).toHaveURL(/\/login$/);});
