import { StrictMode } from 'react';
import { describe,it,expect,vi } from 'vitest';
import { render,screen,waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router';
import { AuthV2Routes } from '../../src/auth-v2/app';
import { AuthProviderV2 } from '../../src/auth-v2/provider';
import { SessionStore } from '../../src/auth-v2/session';
import type { AuthClientV2 } from '../../src/auth-v2/client';
import { AppProviders } from '../../src/app/providers';
import { createServices } from '../../src/app/services';
import { publicConfig } from '../../src/config/env';
import { publicEnv,session,profile } from '../helpers';
import { debtFixture,debtViewFixture,debtPaymentFixture,debtSummaryFixture,debtSimulationFixture } from '../fixtures/debts';
import { bankAccount,expenseCategory,cardAccount } from '../fixtures/cards';
function setup(path='/finance/debts',handler?:(url:URL,options?:RequestInit)=>Response,signedIn=true){const client={auth:{onAuthStateChange:vi.fn(),signOut:vi.fn()}} as unknown as AuthClientV2,store=new SessionStore(client.auth);store.accept(signedIn?session:null);const writes:{path:string;body:Record<string,unknown>}[]=[];const fetcher=vi.fn<typeof fetch>(async(url,options)=>{const parsed=new URL(String(url));if(parsed.pathname.endsWith('/me'))return Response.json({identity:{authUserId:session.user.id},profile});if(options?.method!=='GET')writes.push({path:parsed.pathname,body:JSON.parse(String(options?.body))});return handler?.(parsed,options)??defaults(parsed,options);});const services=createServices(publicConfig(publicEnv),store,fetcher);render(<StrictMode><AuthProviderV2 client={client} store={store}><AppProviders services={services}><MemoryRouter initialEntries={[path]}><AuthV2Routes/></MemoryRouter></AppProviders></AuthProviderV2></StrictMode>);return {user:userEvent.setup(),writes,fetcher};}
function defaults(url:URL,options?:RequestInit){const p=url.pathname;if(options?.method==='POST')return Response.json(p.endsWith('/payments')?debtPaymentFixture:p.endsWith('/simulate')?debtSimulationFixture:debtFixture,{status:p.endsWith('/simulate')||p.endsWith('/cancel')||p.endsWith('/archive')?200:201});if(p.endsWith('/accounts'))return Response.json([bankAccount,cardAccount]);if(p.endsWith('/categories'))return Response.json([expenseCategory]);if(p.endsWith('/items'))return Response.json({items:[],nextCursor:null});if(p.endsWith('/summary'))return Response.json(debtSummaryFixture);if(p.endsWith('/payments'))return Response.json({items:[],nextCursor:null});return Response.json(p.endsWith('/debts')?[debtFixture]:debtViewFixture());}
describe('debt frontend protected boundary',()=>{
  it('dashboard displays actual principal, rate and minimum; reads only',async()=>{const {fetcher}=setup();expect(await screen.findByRole('heading',{name:'Dívida teste · BRL'})).toBeVisible();expect(await screen.findByText('Principal real restante')).toBeVisible();expect(screen.getByText(/Taxa efetiva: 12% anual/)).toBeVisible();expect(fetcher.mock.calls.every(([,o])=>o?.method==='GET')).toBe(true);});
  it('create uses positive exact principal, explicit percentage fraction and no owner',async()=>{const {user,writes}=setup();await screen.findByRole('heading',{name:'Dívida teste · BRL'});await user.click(screen.getByRole('button',{name:'Nova dívida'}));await user.type(screen.getByLabelText('Nome da dívida'),'Nova teste');await user.type(screen.getByLabelText('Principal atual (valor positivo)'),'10000');await user.click(screen.getByRole('button',{name:'Salvar dívida'}));await waitFor(()=>expect(writes).toHaveLength(1));expect(writes[0]!.body).toMatchObject({initialPrincipalMinor:'1000000',rate:'0.12',minimumPaymentMinor:'50000',ratePeriod:'EFFECTIVE_ANNUAL'});expect(writes[0]!.body).not.toHaveProperty('authUserId');});
  it('real payment separates principal and costs, exact preview and single command in StrictMode',async()=>{const {user,writes}=setup('/finance/debts/'+debtFixture.id);await screen.findByRole('heading',{name:'Saldo real e pagamentos'});await user.click(screen.getByRole('button',{name:'Registrar pagamento real'}));expect(screen.getByText(/Somente principal reduz o saldo devedor/)).toBeVisible();await user.selectOptions(screen.getByLabelText('Conta de origem'),bankAccount.id);await user.type(screen.getByLabelText('Principal pago (BRL)'),'400');await user.clear(screen.getByLabelText('Juros pagos (BRL)'));await user.type(screen.getByLabelText('Juros pagos (BRL)'),'90');await user.clear(screen.getByLabelText('Tarifas pagas (BRL)'));await user.type(screen.getByLabelText('Tarifas pagas (BRL)'),'10');expect(screen.getByText(/Total debitado:.*500,00/)).toBeVisible();expect(screen.getByText(/Principal restante:.*9.600,00/)).toBeVisible();expect(screen.queryByRole('option',{name:/Conta credit/})).not.toBeInTheDocument();await user.dblClick(screen.getByRole('button',{name:'Registrar pagamento'}));await waitFor(()=>expect(writes).toHaveLength(1));expect(writes[0]!.body).toMatchObject({principalAmountMinor:'40000',interestAmountMinor:'9000',feeAmountMinor:'1000'});expect(writes[0]!.path).toMatch(/debts\/.*\/payments$/);});
  it('uncertain payment retry keeps idempotency key and payload',async()=>{const {user,writes}=setup('/finance/debts/'+debtFixture.id,(url,o)=>url.pathname.endsWith('/payments')&&o?.method==='POST'?Response.json({error:{code:'CONFLICT',message:'Resource conflict.',requestId:'test'}},{status:409}):defaults(url,o));await screen.findByRole('heading',{name:'Saldo real e pagamentos'});await user.click(screen.getByRole('button',{name:'Registrar pagamento real'}));await user.selectOptions(screen.getByLabelText('Conta de origem'),bankAccount.id);await user.type(screen.getByLabelText('Principal pago (BRL)'),'400');await user.click(screen.getByRole('button',{name:'Registrar pagamento'}));await waitFor(()=>expect(writes).toHaveLength(1));await screen.findByRole('alert');await user.click(screen.getByRole('button',{name:'Registrar pagamento'}));await waitFor(()=>expect(writes).toHaveLength(2));expect(writes[0]!.body).toEqual(writes[1]!.body);});
  it('simulation renders only server results and posts no ledger mutations',async()=>{const {user,writes}=setup();await screen.findByRole('heading',{name:'Dívida teste · BRL'});await user.click(screen.getByRole('checkbox',{name:'Dívida teste'}));await user.click(screen.getByRole('button',{name:'Comparar estratégias'}));expect(await screen.findByRole('heading',{name:'Avalanche — maior taxa mensal'})).toBeVisible();expect(screen.getByRole('heading',{name:'Snowball — menor principal'})).toBeVisible();expect(writes).toHaveLength(1);expect(writes[0]!.body).toMatchObject({strategy:'COMPARE',extraMonthlyMinor:'50000',debtIds:[debtFixture.id]});expect(writes[0]!.path).toMatch(/debts\/simulate$/);});
  it('paid-off debt disables further payments but allows archive',async()=>{setup('/finance/debts/'+debtFixture.id,(url,o)=>url.pathname.endsWith('/'+debtFixture.id)?Response.json(debtViewFixture({debt:{...debtFixture,status:'PAID_OFF',paidOffAt:debtFixture.createdAt},outstandingPrincipalMinor:'0',nextDueDate:null})):defaults(url,o));await screen.findByRole('heading',{name:'Saldo real e pagamentos'});expect(screen.getByRole('button',{name:'Registrar pagamento real'})).toBeDisabled();expect(screen.getByRole('button',{name:'Arquivar dívida quitada'})).toBeEnabled();});
  it('foreign/missing debt displays error without private records',async()=>{setup('/finance/debts/'+debtFixture.id,(url,o)=>url.pathname.endsWith('/'+debtFixture.id)?Response.json({error:{code:'NOT_FOUND',message:'Resource not found.',requestId:'test'}},{status:404}):defaults(url,o));expect(await screen.findByRole('heading',{name:'Dívida indisponível'})).toBeVisible();expect(screen.queryByText('Dívida teste')).not.toBeInTheDocument();});
  it('signed-out route redirects before any financial request',async()=>{const {fetcher}=setup('/finance/debts',undefined,false);expect(await screen.findByRole('heading',{name:/Bom ter você aqui/})).toBeVisible();expect(fetcher).not.toHaveBeenCalled();});
});
