import { StrictMode } from 'react';
import { describe, it, expect, vi } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router';
import { AuthV2Routes } from '../../src/auth-v2/app';
import { AuthProviderV2 } from '../../src/auth-v2/provider';
import { SessionStore } from '../../src/auth-v2/session';
import type { AuthClientV2 } from '../../src/auth-v2/client';
import { AppProviders } from '../../src/app/providers';
import { createServices } from '../../src/app/services';
import { publicConfig } from '../../src/config/env';
import { publicEnv, session, profile, deferred } from '../helpers';
import { goalFixture } from '../fixtures/goals';
function setup(fetcher: typeof fetch, path = '/finance/goals', signedIn = true) { const client = { auth: { onAuthStateChange: vi.fn(), signOut: vi.fn() } } as unknown as AuthClientV2; const store = new SessionStore(client.auth); store.accept(signedIn ? session : null); const services = createServices(publicConfig(publicEnv), store, fetcher); render(<StrictMode><AuthProviderV2 client={client} store={store}><AppProviders services={services}><MemoryRouter initialEntries={[path]}><AuthV2Routes /></MemoryRouter></AppProviders></AuthProviderV2></StrictMode>); return { user: userEvent.setup(), store }; }
const boundary = (handler: (url: URL, options?: RequestInit) => Promise<Response> | Response): typeof fetch => async (url, options) => { const parsed = new URL(String(url)); if (parsed.pathname.endsWith('/me')) return Response.json({ identity: { authUserId: session.user.id }, profile }); return handler(parsed, options); };
describe('goal routes with authenticated data boundary', () => {
  it('shows first-use planning semantics and no invented balance', async () => { setup(boundary(() => Response.json([]))); expect(await screen.findByText('Crie sua primeira meta financeira')).toBeVisible(); expect(screen.getByText(/não movimenta suas contas/)).toBeVisible(); });
  it('shows backend-derived >100% progress, statuses and separate currencies', async () => { setup(boundary(() => Response.json([goalFixture({ currentAmountMinor: '1200000', remainingAmountMinor: '0', progressPercent: '120.00', planStatus: 'ACHIEVED' }), goalFixture({ id: '88888888-8888-4888-8888-888888888888', name: 'Viagem USD', currency: 'USD', status: 'PAUSED' })]))); expect(await screen.findByText('120% do valor alvo')).toBeVisible(); expect(screen.getByText('Meta atingida')).toBeVisible(); expect(screen.getByRole('progressbar', { name: 'Progresso de Reserva teste' })).toHaveAttribute('aria-valuenow', '100'); expect(screen.getByText('BRL · METAS EXIBIDAS')).toBeVisible(); expect(screen.getByText('USD · METAS EXIBIDAS')).toBeVisible(); });
  it('uses URL filters and never sends an ownership identifier', async () => { const urls: string[] = []; const { user } = setup(boundary(url => { urls.push(url.search); return Response.json([]); })); await screen.findByText('Crie sua primeira meta financeira'); await user.selectOptions(screen.getByLabelText('Status'), 'PAUSED'); await user.selectOptions(screen.getByLabelText('Filtrar moeda'), 'USD'); await waitFor(() => expect(urls).toContain('?status=PAUSED&currency=USD')); expect(urls.join()).not.toMatch(/owner|auth_user/); });
  it('blocks negative withdrawal locally and preserves idempotency key after uncertain failure', async () => { const writes: Record<string, unknown>[] = []; const goal = goalFixture({ currentAmountMinor: '250000', remainingAmountMinor: '750000', progressPercent: '25.00' }); const { user } = setup(boundary((url, options) => { if (options?.method === 'POST') { writes.push(JSON.parse(String(options.body))); return Response.json({}, { status: 503 }); } return Response.json(url.pathname.endsWith('/events') ? { items: [], nextCursor: null } : goal); }), '/finance/goals/' + goal.id); await screen.findByRole('heading', { name: goal.name }); await user.click(screen.getByRole('button', { name: 'Retirar valor' })); await user.type(screen.getByLabelText('Valor em BRL'), '3000'); await user.click(screen.getByRole('button', { name: 'Registrar retirada' })); expect(await screen.findByText(/retirada não pode superar/)).toBeVisible(); expect(writes).toHaveLength(0); await user.clear(screen.getByLabelText('Valor em BRL')); await user.type(screen.getByLabelText('Valor em BRL'), '500'); await user.click(screen.getByRole('button', { name: 'Registrar retirada' })); await screen.findByText('Não foi possível concluir a solicitação. Tente novamente.'); await user.click(screen.getByRole('button', { name: 'Registrar retirada' })); await waitFor(() => expect(writes).toHaveLength(2)); expect(writes[0]).toEqual(writes[1]); expect(writes[0]).toMatchObject({ amountMinor: '50000', type: 'WITHDRAWAL' }); expect(writes[0]).not.toHaveProperty('auth_user_id'); });
  it('shows paused/archived history and blocks event buttons', async () => { const g = goalFixture({ status: 'ARCHIVED', archivedAt: '2026-10-01T12:00:00Z' }); setup(boundary(url => Response.json(url.pathname.endsWith('/events') ? { items: [], nextCursor: null } : g)), '/finance/goals/' + g.id); expect(await screen.findByText(/Meta arquivada/)).toBeVisible(); expect(screen.queryByRole('button', { name: 'Adicionar valor' })).not.toBeInTheDocument(); expect(screen.getByRole('heading', { name: 'Histórico da meta' })).toBeVisible(); });
  it('shows loading and safe API errors without claiming success', async () => { const pending = deferred<Response>(); setup(boundary(() => pending.promise)); expect(await screen.findByRole('status')).toHaveTextContent('Carregando metas'); pending.resolve(Response.json({}, { status: 503 })); expect(await screen.findByText('Não foi possível carregar suas metas. Tente novamente.')).toBeVisible(); });
  it('does not query protected goal data without a session', async () => { const fetcher = vi.fn<typeof fetch>(); setup(fetcher, '/finance/goals', false); expect(await screen.findByRole('heading', { name: 'Bom ter você aqui.' })).toBeVisible(); expect(fetcher).not.toHaveBeenCalled(); });
});
