import { StrictMode } from 'react';
import { describe,it,expect,vi } from 'vitest';
import { render,screen,waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router';
import { AuthV2Routes } from '../../src/auth-v2/app';
import { AuthProviderV2 } from '../../src/auth-v2/provider';
import { SessionStore } from '../../src/auth-v2/session';
import type { AuthClientV2 } from '../../src/auth-v2/client';
import { AppProviders } from '../../src/app/providers';
import { createServices } from '../../src/app/services';
import { publicConfig } from '../../src/config/env';
import { publicEnv,session,profile } from '../helpers';
import { netWorthSummary,netWorthHistory,netWorthItem } from '../fixtures/net-worth';
function setup(handler:(url:URL,options?:RequestInit)=>Response,signedIn=true){const client={auth:{onAuthStateChange:vi.fn(),signOut:vi.fn()}} as unknown as AuthClientV2;const store=new SessionStore(client.auth);store.accept(signedIn?session:null);const fetcher=vi.fn<typeof fetch>(async(url,options)=>{const parsed=new URL(String(url));if(parsed.pathname.endsWith('/me'))return Response.json({identity:{authUserId:session.user.id},profile});return handler(parsed,options);});const services=createServices(publicConfig(publicEnv),store,fetcher);render(<StrictMode><AuthProviderV2 client={client} store={store}><AppProviders services={services}><MemoryRouter initialEntries={['/finance/net-worth']}><AuthV2Routes/></MemoryRouter></AppProviders></AuthProviderV2></StrictMode>);return{user:userEvent.setup(),fetcher};}
const defaults=(url:URL)=>Response.json(url.pathname.endsWith('/history')?netWorthHistory:url.pathname.endsWith('/items')?{items:[],nextCursor:null}:netWorthSummary);
describe('net worth authenticated boundary',()=>{
 it('shows signed read-only accounts, exact totals and accessible history without writes',async()=>{const {fetcher}=setup(defaults);expect(await screen.findByText('Conta principal · Conta inativa')).toBeVisible();expect(screen.getByText(/Saldos das contas são somente leitura/)).toBeVisible();expect(await screen.findByRole('table')).toBeVisible();expect(screen.getByText(/Evite cadastrar novamente/)).toBeVisible();expect(fetcher.mock.calls.every(([,o])=>!o?.method||o.method==='GET')).toBe(true);});
 it('creates using exact money, no owner, and blocks zero initial/future dates',async()=>{const writes:Record<string,unknown>[]=[];const {user}=setup((url,o)=>{if(o?.method==='POST'){const body=JSON.parse(String(o.body));writes.push(body);return Response.json(netWorthItem(),{status:201});}return defaults(url);});await screen.findByRole('heading',{name:'Patrimônio'});await user.click(screen.getByRole('button',{name:'Novo item'}));await user.type(screen.getByLabelText('Nome',{exact:true}),'Carro teste');await user.type(screen.getByLabelText('Valor em BRL'),'0');await user.click(screen.getByRole('button',{name:'Cadastrar item'}));expect(writes).toHaveLength(0);await user.clear(screen.getByLabelText('Valor em BRL'));await user.type(screen.getByLabelText('Valor em BRL'),'123,45');await user.click(screen.getByRole('button',{name:'Cadastrar item'}));await waitFor(()=>expect(writes).toHaveLength(1));expect(writes[0]).toMatchObject({name:'Carro teste',initialValueMinor:'12345',kind:'ASSET',currency:'BRL'});expect(writes[0]).not.toHaveProperty('auth_user_id');expect(writes[0]).not.toHaveProperty('owner');});
 it('keeps archived items read-only and valuation history available',async()=>{const item=netWorthItem({status:'ARCHIVED',archivedAt:'2026-10-05T12:00:00Z'});const {user}=setup(url=>url.pathname.endsWith('/valuations')?Response.json({items:[item.latestValuation],nextCursor:null}):url.pathname.endsWith('/items')?Response.json({items:[item],nextCursor:null}):defaults(url));await screen.findByRole('heading',{name:item.name});expect(screen.queryByRole('button',{name:'Editar dados'})).toBeNull();expect(screen.queryByRole('button',{name:'Nova avaliação'})).toBeNull();await user.click(screen.getByRole('button',{name:'Ver histórico'}));expect(await screen.findByRole('heading',{name:'Histórico de avaliações — '+item.name})).toBeVisible();});
 it('switches currency and date on reads, without inventing FX or writing ledger',async()=>{const calls:string[]=[];const {user}=setup(url=>{calls.push(url.pathname+url.search);return defaults(url);});await screen.findByRole('heading',{name:'Composição — BRL'});await user.selectOptions(screen.getByLabelText('Moeda do patrimônio'),'USD');await waitFor(()=>expect(calls.some(c=>c.includes('/history?')&&c.includes('currency=USD'))).toBe(true));expect(await screen.findByRole('heading',{name:'Composição — USD'})).toBeVisible();expect(calls.every(c=>c.includes('/net-worth'))).toBe(true);});
 it('protects the route before reading private data',async()=>{const {fetcher}=setup(defaults,false);expect(await screen.findByRole('heading',{name:'Bom ter você aqui.'})).toBeVisible();expect(fetcher).not.toHaveBeenCalled();});
});
