import { StrictMode } from 'react';
import { describe,it,expect,vi } from 'vitest';
import { render,screen,waitFor,within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router';
import { AuthV2Routes } from '../../src/auth-v2/app';
import { AuthProviderV2 } from '../../src/auth-v2/provider';
import { SessionStore } from '../../src/auth-v2/session';
import type { AuthClientV2 } from '../../src/auth-v2/client';
import { AppProviders } from '../../src/app/providers';
import { createServices } from '../../src/app/services';
import { publicConfig } from '../../src/config/env';
import { publicEnv,session,profile,deferred } from '../helpers';
import { accountFixture,categoryFixture,recurrenceFixture,entryFixture,calendarFixture,radarFixture } from '../fixtures/recurrences';
import type { Recurrence,SubscriptionRadar } from '../../src/features/finance/contracts.generated';
function setup(fetcher:typeof fetch,path='/finance/recurrences',signedIn=true){const client={auth:{onAuthStateChange:vi.fn(),signOut:vi.fn()}} as unknown as AuthClientV2;const store=new SessionStore(client.auth);store.accept(signedIn?session:null);const services=createServices(publicConfig(publicEnv),store,fetcher);render(<StrictMode><AuthProviderV2 client={client} store={store}><AppProviders services={services}><MemoryRouter initialEntries={[path]}><AuthV2Routes/></MemoryRouter></AppProviders></AuthProviderV2></StrictMode>);return {user:userEvent.setup(),store};}
const boundary=(handler:(url:URL,options?:RequestInit)=>Promise<Response>|Response,radar:SubscriptionRadar=radarFixture()):typeof fetch=>async(url,options)=>{const parsed=new URL(String(url));if(parsed.pathname.endsWith('/me'))return Response.json({identity:{authUserId:session.user.id},profile});if(parsed.pathname.endsWith('/accounts'))return Response.json([accountFixture,{...accountFixture,id:'55555555-5555-4555-8555-555555555555',name:'Conta USD',currency:'USD'}]);if(parsed.pathname.endsWith('/categories'))return Response.json([categoryFixture,{...categoryFixture,id:'66666666-6666-4666-8666-666666666666',name:'Salário',kind:'INCOME'}]);if(parsed.pathname.endsWith('/subscriptions/radar'))return Response.json(radar);return handler(parsed,options);};
describe('recurrence and calendar authenticated UI boundaries',()=>{
  it('shows first use and planning semantics without financial writes',async()=>{const writes:unknown[]=[];setup(boundary((_url,o)=>{if(o?.method&&o.method!=='GET')writes.push(o);return Response.json({items:[],nextCursor:null});}));expect(await screen.findByText('Nenhuma recorrência cadastrada')).toBeVisible();expect(screen.getByText(/não criam lançamentos nem alteram contas/)).toBeVisible();expect(screen.getByText('Nenhuma assinatura ativa.')).toBeVisible();expect(writes).toHaveLength(0);});
  it('creates a subscription with exact money, DATE, compatible references and no owner',async()=>{let row:Recurrence|null=null;const writes:Record<string,unknown>[]=[];const {user}=setup(boundary((_url,o)=>{if(o?.method==='POST'){const body=JSON.parse(String(o.body));writes.push(body);row=recurrenceFixture(body);return Response.json(row,{status:201});}return Response.json({items:row?[row]:[],nextCursor:null});}));await screen.findByText('Nenhuma recorrência cadastrada');await user.click(screen.getByRole('button',{name:'Nova recorrência'}));await user.type(screen.getByLabelText('Nome',{exact:true}),'Assinatura teste');await user.selectOptions(screen.getByRole('combobox',{name:'Tipo'}),'INCOME');await user.selectOptions(screen.getByRole('combobox',{name:'Classificação'}),'SUBSCRIPTION');expect(screen.getByRole('combobox',{name:'Tipo'})).toBeDisabled();expect(screen.getByRole('combobox',{name:'Tipo'})).toHaveValue('EXPENSE');expect(within(screen.getByLabelText('Conta opcional')).queryByRole('option',{name:'Conta USD'})).toBeNull();expect(within(screen.getByLabelText('Categoria opcional')).queryByRole('option',{name:'Salário'})).toBeNull();await user.type(screen.getByLabelText('Valor em BRL'),'100,00');await user.type(screen.getByLabelText('Data inicial'),'2026-10-31');await user.selectOptions(screen.getByLabelText('Conta opcional'),accountFixture.id);await user.selectOptions(screen.getByLabelText('Categoria opcional'),categoryFixture.id);await user.click(screen.getByRole('button',{name:'Cadastrar recorrência'}));await screen.findByText('Recorrência cadastrada.');expect(writes).toHaveLength(1);expect(writes[0]).toMatchObject({amountMinor:'10000',startDate:'2026-10-31',transactionType:'EXPENSE',recurrenceKind:'SUBSCRIPTION',accountId:accountFixture.id,categoryId:categoryFixture.id});expect(writes[0]).not.toHaveProperty('owner');expect(writes[0]).not.toHaveProperty('auth_user_id');});
  it('blocks invalid amount, interval and end date without requesting a write',async()=>{const writes:unknown[]=[];const {user}=setup(boundary((_url,o)=>{if(o?.method&&o.method!=='GET')writes.push(o);return Response.json({items:[],nextCursor:null});}));await screen.findByText('Nenhuma recorrência cadastrada');await user.click(screen.getByRole('button',{name:'Nova recorrência'}));await user.type(screen.getByLabelText('Nome',{exact:true}),'Inválida');await user.type(screen.getByLabelText('Valor em BRL'),'-1');await user.clear(screen.getByLabelText('Intervalo'));await user.type(screen.getByLabelText('Intervalo'),'25');await user.type(screen.getByLabelText('Data inicial'),'2026-10-31');await user.type(screen.getByLabelText('Data final opcional'),'2026-10-01');await user.click(screen.getByRole('button',{name:'Cadastrar recorrência'}));expect(await screen.findByText('Use um intervalo de 1 a 24.')).toBeVisible();expect(screen.getByText(/data final deve ser válida/)).toBeVisible();expect(screen.getByLabelText('Valor em BRL')).toHaveAttribute('aria-invalid','true');expect(writes).toHaveLength(0);});
  it('edits while keeping type/currency fixed and uses explicit status endpoints',async()=>{let row=recurrenceFixture();const writes:{path:string;body:Record<string,unknown>}[]=[];const {user}=setup(boundary((url,o)=>{if(o?.method&&o.method!=='GET'){const body=JSON.parse(String(o.body));writes.push({path:url.pathname,body});row={...row,...body,...(url.pathname.endsWith('/pause')?{status:'PAUSED' as const,nextOccurrenceDate:null}:url.pathname.endsWith('/resume')?{status:'ACTIVE' as const,nextOccurrenceDate:'2026-10-31'}:url.pathname.endsWith('/archive')?{status:'ARCHIVED' as const,nextOccurrenceDate:null,archivedAt:'2026-10-02T12:00:00Z'}:{})};return Response.json(row);}return Response.json({items:[row],nextCursor:null});}));await screen.findByRole('heading',{name:row.name});await user.click(screen.getByRole('button',{name:'Editar '+row.name}));expect(screen.getByRole('combobox',{name:'Moeda'})).toBeDisabled();expect(screen.getByRole('combobox',{name:'Tipo'})).toBeDisabled();await user.clear(screen.getByLabelText('Valor em BRL'));await user.type(screen.getByLabelText('Valor em BRL'),'150');await user.click(screen.getByRole('button',{name:'Salvar alterações'}));await screen.findByText('Recorrência atualizada.');expect(writes[0]?.body).toMatchObject({amountMinor:'15000'});expect(writes[0]?.body).not.toHaveProperty('currency');await user.click(screen.getByRole('button',{name:'Pausar'}));await screen.findByRole('button',{name:'Retomar'});await user.click(screen.getByRole('button',{name:'Retomar'}));await screen.findByRole('button',{name:'Pausar'});await user.click(screen.getByRole('button',{name:'Arquivar'}));expect(writes).toHaveLength(3);await user.click(screen.getByRole('button',{name:'Confirmar arquivamento'}));expect(await screen.findByText('Arquivada',{exact:true,selector:'span'})).toBeVisible();expect(screen.queryByRole('button',{name:'Retomar'})).toBeNull();expect(writes.slice(1).map(w=>w.path.split('/').at(-1))).toEqual(['pause','resume','archive']);expect(writes.slice(1).every(w=>Object.keys(w.body).length===0)).toBe(true);});
  it('sends URL filters and both pagination cursor fields without ownership identifiers',async()=>{const reads:string[]=[];const a=recurrenceFixture(),b=recurrenceFixture({id:'77777777-7777-4777-8777-777777777777',name:'Segunda'});const {user}=setup(boundary(url=>{reads.push(url.search);return Response.json(url.searchParams.has('cursorId')?{items:[b],nextCursor:null}:{items:[a],nextCursor:{createdAt:a.createdAt,id:a.id}});}));await screen.findByRole('heading',{name:a.name});await user.click(screen.getByRole('button',{name:'Carregar mais recorrências'}));await screen.findByRole('heading',{name:'Segunda'});expect(reads.some(s=>s.includes('cursorId='+a.id)&&s.includes('cursorAt='))).toBe(true);await user.selectOptions(screen.getByLabelText('Status das recorrências'),'PAUSED');await user.selectOptions(screen.getByLabelText('Moeda das recorrências'),'USD');await waitFor(()=>expect(reads.some(s=>s.includes('status=PAUSED')&&s.includes('currency=USD'))).toBe(true));expect(reads.join()).not.toMatch(/owner|auth_user/);});
  it('renders server calendar entries, exact totals per currency and half-open month navigation',async()=>{const calls:string[]=[];const a=recurrenceFixture(),b=recurrenceFixture({id:'77777777-7777-4777-8777-777777777777',name:'Receita mensal',transactionType:'INCOME',recurrenceKind:'STANDARD',amountMinor:'50000'}),c=recurrenceFixture({id:'88888888-8888-4888-8888-888888888888',name:'USD anual',currency:'USD',frequency:'YEARLY',amountMinor:'3000'});const {user}=setup(boundary(url=>{calls.push(url.search);return Response.json(calendarFixture([entryFixture(a),entryFixture(b),entryFixture(c)],url.searchParams.get('from')!,url.searchParams.get('to')!));}),'/finance/calendar?month=2026-10');expect(await screen.findAllByText('Líquido previsto')).toHaveLength(2);expect(screen.getByText(/não é saldo disponível/)).toBeVisible();expect(screen.getByText('BRL',{selector:'h3'})).toBeVisible();expect(screen.getByText('USD',{selector:'h3'})).toBeVisible();expect(screen.getByText('Receita prevista · Recorrência')).toBeVisible();expect(screen.getByText('31/10/2026',{selector:'time'})).toBeVisible();await user.click(screen.getByRole('button',{name:'Próximo mês'}));await waitFor(()=>expect(calls.some(s=>s.includes('from=2026-11-01')&&s.includes('to=2026-12-01'))).toBe(true));await user.selectOptions(screen.getByLabelText('Moeda do calendário'),'USD');await waitFor(()=>expect(calls.some(s=>s.includes('currency=USD'))).toBe(true));expect(calls.join()).not.toMatch(/transactions|owner/);});
  it('keeps loading and service errors visible with an explicit retry',async()=>{const pending=deferred<Response>();let failed=true;const {user}=setup(boundary(()=>failed?pending.promise:Response.json({items:[],nextCursor:null})));expect(await screen.findByText('Carregando recorrências…')).toBeVisible();pending.resolve(Response.json({},{status:503}));expect(await screen.findByText('Não foi possível carregar suas recorrências.')).toBeVisible();failed=false;await user.click(screen.getByRole('button',{name:'Tentar novamente recorrências'}));expect(await screen.findByText('Nenhuma recorrência cadastrada')).toBeVisible();});
  it('renders actual weekly radar charges per currency, including a future subscription with no charge',async()=>{const brl=recurrenceFixture({frequency:'WEEKLY',startDate:'2026-10-02',nextOccurrenceDate:'2026-10-02'}),usd=recurrenceFixture({id:'88888888-8888-4888-8888-888888888888',name:'USD futura',currency:'USD',startDate:'2027-01-31',nextOccurrenceDate:'2027-01-31'}),entries=['2026-10-02','2026-10-09','2026-10-16','2026-10-23','2026-10-30'].map(date=>entryFixture(brl,date));const {user}=setup(boundary(()=>Response.json({items:[brl,usd],nextCursor:null}),radarFixture([brl,usd],entries)));expect(await screen.findByText('5 cobranças previstas em 30 dias')).toBeVisible();expect(screen.getByText('0 cobranças previstas em 30 dias')).toBeVisible();await user.click(screen.getByText('Assinaturas ativas (2)'));expect(screen.getByText('Próxima: 31/01/2027')).toBeVisible();expect(screen.getByText('USD · 1 assinatura ativa')).toBeVisible();});
  it('shows calendar service error and retry without fictional entries',async()=>{let failed=true;const {user}=setup(boundary(()=>failed?Response.json({},{status:503}):Response.json(calendarFixture())),'/finance/calendar?month=2026-10');expect(await screen.findByText('Não foi possível carregar o calendário financeiro.')).toBeVisible();failed=false;await user.click(screen.getByRole('button',{name:'Tentar novamente calendário'}));expect(await screen.findByText('Nenhuma ocorrência prevista neste período.')).toBeVisible();expect(screen.getByText('Sem valores recorrentes previstos no período.')).toBeVisible();});
  it.each(['/finance/recurrences','/finance/calendar'])('protects %s without reading private data',async path=>{const fetcher=vi.fn<typeof fetch>();setup(fetcher,path,false);expect(await screen.findByRole('heading',{name:'Entrar'})).toBeVisible();expect(fetcher).not.toHaveBeenCalled();});
});
