import { StrictMode } from 'react';
import { describe,it,expect,vi } from 'vitest';
import { render,screen,waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router';
import { AuthV2Routes } from '../../src/auth-v2/app';
import { AuthProviderV2 } from '../../src/auth-v2/provider';
import { SessionStore } from '../../src/auth-v2/session';
import type { AuthClientV2 } from '../../src/auth-v2/client';
import { AppProviders } from '../../src/app/providers';
import { createServices } from '../../src/app/services';
import { publicConfig } from '../../src/config/env';
import { publicEnv,session,profile } from '../helpers';
import { safeSettings,safeView } from '../fixtures/safe-spend';
import { bankAccount,cardAccount } from '../fixtures/cards';
import type { SafeSpendSettings,SafeSpendView } from '../../src/features/finance/contracts.generated';
function setup(configured=true,override?:Partial<SafeSpendView>,signedIn=true){const client={auth:{onAuthStateChange:vi.fn(),signOut:vi.fn()}} as unknown as AuthClientV2,store=new SessionStore(client.auth);store.accept(signedIn?session:null);let config:SafeSpendSettings|null=configured?{...safeSettings}:null;const writes:unknown[]=[],fetcher=vi.fn<typeof fetch>(async(url,options)=>{const u=new URL(String(url));if(u.pathname.endsWith('/me'))return Response.json({identity:{authUserId:session.user.id},profile});if(u.pathname.endsWith('/accounts'))return Response.json([bankAccount,cardAccount]);if(options?.method==='PUT'){const input=JSON.parse(String(options.body));writes.push(input);config={...safeSettings,...input};return Response.json(config);}if(u.pathname.endsWith('/settings'))return Response.json(config);return Response.json({...safeView,...override});});const services=createServices(publicConfig(publicEnv),store,fetcher);render(<StrictMode><AuthProviderV2 client={client} store={store}><AppProviders services={services}><MemoryRouter initialEntries={['/finance/safe-to-spend']}><AuthV2Routes/></MemoryRouter></AppProviders></AuthProviderV2></StrictMode>);return {user:userEvent.setup(),writes,fetcher};}
describe('Safe Spend protected UI integration',()=>{
  it('onboarding has no invented headline and no automatic account selection',async()=>{setup(false);expect(await screen.findByRole('heading',{name:'Configurar dinheiro disponível'})).toBeVisible();expect(screen.queryByTestId('safe-spend-headline')).not.toBeInTheDocument();expect(screen.getAllByRole('checkbox')[0]).not.toBeChecked();expect(screen.queryByRole('checkbox',{name:/Conta credit/})).not.toBeInTheDocument();});
  it('settings capture current explicit selection; StrictMode/double click writes once, no ledger writes',async()=>{const {user,writes}=setup(false);await screen.findByRole('heading',{name:'Configurar dinheiro disponível'});await user.click(screen.getAllByRole('checkbox')[0]!);await user.clear(screen.getByLabelText('Quanto deseja manter intocado? (BRL)'));await user.type(screen.getByLabelText('Quanto deseja manter intocado? (BRL)'),'500');await user.dblClick(screen.getByRole('button',{name:'Salvar configuração'}));await waitFor(()=>expect(writes).toHaveLength(1));expect(writes[0]).toMatchObject({accountIds:[bankAccount.id],safetyBufferMinor:'50000',respectBudget:true});expect(writes[0]).not.toHaveProperty('ownerId');expect(await screen.findByTestId('safe-spend-headline')).toHaveTextContent('1.800,00');});
  it('breakdown, certainty labels and expected-income isolation use server results, read-only',async()=>{const {writes}=setup();expect(await screen.findByTestId('safe-spend-headline')).toHaveTextContent('1.800,00');for(const name of ['Como o valor foi calculado','Se as receitas previstas entrarem','Fontes e reservas consideradas'])expect(screen.getByRole('heading',{name})).toBeVisible();expect(screen.getByText(/Confirmado · Considerado/)).toBeVisible();expect(screen.getByText(/Projetado · Excluído/)).toBeVisible();expect(screen.getByText(/Orçamento é teto/)).toBeVisible();expect(writes).toHaveLength(0);});
  it('shortfall floors headline and budget overrun remains distinct from cash',async()=>{setup(true,{status:'OVERCOMMITTED',safeToSpendMinor:'0',cashCapacityMinor:'-50000',rawSafeToSpendMinor:'-50000',shortfallMinor:'50000',budgetOverrunMinor:'10000'});expect(await screen.findByTestId('safe-spend-headline')).toHaveTextContent('0,00');expect(screen.getByText(/Faltam.*500,00/)).toBeVisible();expect(screen.getByText(/orçamento mensal já foi excedido/)).toBeVisible();});
  it('empty selection cannot be saved and UI remains neutral on failure',async()=>{const {user,writes}=setup(false);await screen.findByRole('heading',{name:'Configurar dinheiro disponível'});await user.click(screen.getByRole('button',{name:'Salvar configuração'}));expect(await screen.findByRole('alert')).toHaveTextContent('Selecione ao menos uma conta');expect(writes).toHaveLength(0);});
  it('signed-out route guards run before financial data requests',async()=>{const {fetcher}=setup(true,undefined,false);expect(await screen.findByRole('heading',{name:'Entrar'})).toBeVisible();expect(fetcher).not.toHaveBeenCalled();});
});
