import { StrictMode } from 'react';
import { describe,it,expect,vi } from 'vitest';
import { render,screen,waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router';
import { AuthV2Routes } from '../../src/auth-v2/app';
import { AuthProviderV2 } from '../../src/auth-v2/provider';
import { SessionStore } from '../../src/auth-v2/session';
import type { AuthClientV2 } from '../../src/auth-v2/client';
import { AppProviders } from '../../src/app/providers';
import { createServices } from '../../src/app/services';
import { publicConfig } from '../../src/config/env';
import { publicEnv,session,profile } from '../helpers';
import { yieldAccount,yieldProfile,yieldEstimate,yieldBenchmarks,yieldSummary } from '../fixtures/yield';
function setup(handler:(url:URL,o?:RequestInit)=>Response,signedIn=true){const client={auth:{onAuthStateChange:vi.fn(),signOut:vi.fn()}} as unknown as AuthClientV2,store=new SessionStore(client.auth);store.accept(signedIn?session:null);const fetcher=vi.fn<typeof fetch>(async(url,o)=>{const parsed=new URL(String(url));return parsed.pathname.endsWith('/me')?Response.json({identity:{authUserId:session.user.id},profile}):handler(parsed,o);});const services=createServices(publicConfig(publicEnv),store,fetcher);render(<StrictMode><AuthProviderV2 client={client} store={store}><AppProviders services={services}><MemoryRouter initialEntries={['/finance/yield']}><AuthV2Routes/></MemoryRouter></AppProviders></AuthProviderV2></StrictMode>);return {user:userEvent.setup(),fetcher};}
function defaults(url:URL,configured=true){return Response.json(url.pathname.endsWith('/accounts')?[yieldAccount]:url.pathname.endsWith('/profiles')?configured?[yieldProfile()]:[]:url.pathname.endsWith('/benchmarks')?yieldBenchmarks:url.pathname.endsWith('/summary')?yieldSummary:yieldEstimate);}
describe('yield frontend boundary',()=>{
 it('benchmarks current/stale/unavailable, separate currencies, real balance and tax disclosures on GET only',async()=>{const {fetcher}=setup(url=>defaults(url));expect(await screen.findByRole('heading',{name:'Conta rendimento · BRL'})).toBeVisible();expect(screen.getAllByText(/Estimativa — não altera seu saldo/).length).toBeGreaterThan(0);expect(screen.getByRole('heading',{name:'USD · 1 conta(s)'})).toBeVisible();expect(screen.getByText('Usando o último dado disponível.')).toBeVisible();expect(screen.getAllByText('Taxa indisponível no momento.').length).toBeGreaterThan(0);expect(await screen.findByRole('heading',{name:'Projeção — 30 dias'})).toBeVisible();expect(fetcher.mock.calls.every(([,o])=>o?.method==='GET')).toBe(true);});
 it.each(['CDI','SELIC','FIXED_RATE','SAVINGS_BR'] as const)('creates %s profile with one write, exact rate and no ledger access',async type=>{const writes:Record<string,unknown>[]=[];const {user}=setup((url,o)=>{if(o?.method==='POST'){writes.push(JSON.parse(String(o.body)));return Response.json(yieldProfile(),{status:201});}return defaults(url,false);});await screen.findByRole('heading',{name:'Nenhum rendimento configurado'});await user.click(screen.getByRole('button',{name:'Configurar rendimento'}));await user.selectOptions(screen.getByLabelText('Tipo de rendimento'),type);if(type==='CDI'||type==='SELIC'){await user.clear(screen.getByLabelText('Percentual do benchmark (%)'));await user.type(screen.getByLabelText('Percentual do benchmark (%)'),'115');}await user.click(screen.getByRole('button',{name:'Salvar rendimento'}));await waitFor(()=>expect(writes).toHaveLength(1));expect(writes[0]?.ruleType).toBe(type==='CDI'||type==='SELIC'?'BENCHMARK_PERCENTAGE':type);if(type==='CDI'||type==='SELIC')expect(writes[0]?.benchmarkPercentage).toBe('1.15');expect(writes[0]).not.toHaveProperty('ownerId');});
 it('new version, rule history,30/90/365/custom horizons and read-only comparison',async()=>{const writes:string[]=[];const {user,fetcher}=setup((url,o)=>{if(o?.method==='POST'){writes.push(url.pathname);return Response.json(url.pathname.endsWith('/comparison')?{cdi:yieldEstimate,savings:yieldEstimate,fixed:yieldEstimate}:yieldProfile(),{status:url.pathname.endsWith('/versions')?201:200});}return defaults(url);});await screen.findByRole('heading',{name:'Conta rendimento · BRL'});await user.selectOptions(screen.getByLabelText('Prazo da projeção — Conta rendimento'),'90');expect(await screen.findByRole('heading',{name:'Projeção — 90 dias'})).toBeVisible();await user.selectOptions(screen.getByLabelText('Prazo da projeção — Conta rendimento'),'365');expect(await screen.findByRole('heading',{name:'Projeção — 365 dias'})).toBeVisible();await user.click(screen.getByRole('button',{name:'Nova versão — Conta rendimento'}));await user.click(screen.getByRole('button',{name:'Salvar nova versão'}));await waitFor(()=>expect(writes).toHaveLength(1));expect(writes[0]).toContain('/yield-profile/versions');await user.click(screen.getByRole('button',{name:'Comparar rendimentos'}));expect(await screen.findByRole('heading',{name:'100% CDI'})).toBeVisible();expect(writes[1]).toBe('/api/v1/finance/yield/comparison');expect(fetcher.mock.calls.every(([url])=>!String(url).includes('/transactions')&&!String(url).includes('/transfers')&&!String(url).includes('/net-worth'))).toBe(true);});
 it('protects route and preserves inactive/archived history',async()=>{setup(url=>defaults(url),false);expect(await screen.findByRole('heading',{name:'Bom ter você aqui.'})).toBeVisible();});
 it('empty then backend error/retry does not claim a0 return',async()=>{setup(url=>url.pathname.endsWith('/profiles')?Response.json({}, {status:503}):defaults(url));expect(await screen.findByText('Não foi possível carregar as contas.')).toBeVisible();expect(screen.getAllByRole('button',{name:'Tentar novamente'}).length).toBeGreaterThan(0);});
});
