import { Link, useSearchParams } from 'react-router';
import { ArrowDownLeft, ArrowUpRight, CalendarDays, Repeat2 } from 'lucide-react';
import { Button } from '../../components/ui/button';
import { Feedback } from '../../components/feedback';
import { useMe } from '../../profile/hooks';
import { useFinancialCalendar } from './recurrence-hooks';
import { CalendarQuerySchema, currencyDigits } from './contracts.generated';
import type { CalendarEntry } from './contracts.generated';
import { currentBudgetMonth, shiftBudgetMonth, validBudgetMonth, budgetMonthLabel } from './budget-view';
import { civilDateLabel, recurrenceKindLabels, recurrenceTypeLabels } from './recurrence-view';
import { RecurrenceNotice } from './recurrence-pages';
import { formatMoney } from './money';
export function FinancialCalendarPage() {
  const [params,setParams]=useSearchParams(),me=useMe(),locale=me.data?.profile?.locale??'pt-BR';
  const supplied=params.get('month')??'',month=validBudgetMonth(supplied)?supplied:currentBudgetMonth(me.data?.profile?.timezone??'UTC');
  const candidate={from:month+'-01',to:shiftBudgetMonth(month,1)+'-01',...Object.fromEntries(['currency','transactionType','recurrenceKind','accountId','categoryId'].map(k=>[k,params.get(k)]).filter(([,v])=>v))};
  const parsed=CalendarQuerySchema.safeParse(candidate),filters=parsed.success?parsed.data:{from:month+'-01',to:shiftBudgetMonth(month,1)+'-01'};
  const query=useFinancialCalendar(filters),groups=new Map<string,CalendarEntry[]>();
  for(const entry of query.data?.entries??[]){const day=groups.get(entry.date)??[];day.push(entry);groups.set(entry.date,day);}
  const update=(key:string,value:string)=>{const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);setParams(next);};
  return <div className="finance-page financial-calendar"><header className="finance-page-heading"><div><h1 tabIndex={-1}>Calendário financeiro</h1><p>Receitas e despesas previstas pelas suas recorrências cadastradas.</p></div><Button variant="outline" asChild><Link to="/finance/recurrences">Gerenciar recorrências</Link></Button></header><RecurrenceNotice/>
    <section className="finance-panel"><div className="calendar-toolbar"><div className="finance-actions"><Button variant="outline" aria-label="Mês anterior" disabled={!validBudgetMonth(shiftBudgetMonth(month,-1))} onClick={()=>update('month',shiftBudgetMonth(month,-1))}>←</Button><label>Mês do calendário<input type="month" className="finance-select" aria-label="Mês do calendário" min="1000-01" max="9998-12" value={month} onChange={e=>{if(validBudgetMonth(e.target.value))update('month',e.target.value);}}/></label><Button variant="outline" aria-label="Próximo mês" disabled={!validBudgetMonth(shiftBudgetMonth(month,1))} onClick={()=>update('month',shiftBudgetMonth(month,1))}>→</Button></div><h2>{budgetMonthLabel(month,locale)}</h2></div>
      <div className="recurrence-filters calendar-filters"><label>Moeda<select className="finance-select" aria-label="Moeda do calendário" value={filters.currency??''} onChange={e=>update('currency',e.target.value)}><option value="">Todas as moedas</option>{Object.keys(currencyDigits).map(c=><option key={c}>{c}</option>)}</select></label><label>Tipo<select className="finance-select" aria-label="Tipo do calendário" value={filters.transactionType??''} onChange={e=>update('transactionType',e.target.value)}><option value="">Receitas e despesas</option>{Object.entries(recurrenceTypeLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Classificação<select className="finance-select" aria-label="Classificação do calendário" value={filters.recurrenceKind??''} onChange={e=>update('recurrenceKind',e.target.value)}><option value="">Todas as classificações</option>{Object.entries(recurrenceKindLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div>
    </section>
    {query.isPending?<p role="status">Carregando calendário…</p>:query.isError?<section className="finance-panel"><Feedback>Não foi possível carregar o calendário financeiro.</Feedback><Button variant="outline" aria-label="Tentar novamente calendário" onClick={()=>void query.refetch()}>Tentar novamente</Button></section>:query.data&&<>
      <section className="finance-panel" aria-labelledby="calendar-totals"><h2 id="calendar-totals">Resumo previsto do período</h2><p>Receitas recorrentes previstas menos despesas recorrentes previstas. O líquido previsto não é saldo disponível.</p><div className="finance-summary-grid">{query.data.totals.map(t=><div key={t.currency} className="calendar-total"><h3>{t.currency}</h3><dl><div><dt>Receitas previstas</dt><dd>{formatMoney(t.incomeMinor,t.currency,locale)}</dd></div><div><dt>Despesas previstas</dt><dd>{formatMoney(t.expenseMinor,t.currency,locale)}</dd></div><div><dt>Líquido previsto</dt><dd>{formatMoney(t.projectedNetMinor,t.currency,locale)}</dd></div></dl></div>)}</div>{!query.data.totals.length&&<p>Sem valores recorrentes previstos no período.</p>}</section>
      <section className="finance-panel" aria-labelledby="calendar-agenda"><div className="recurrence-section-heading"><div><p className="finance-eyebrow">AGENDA DO MÊS</p><h2 id="calendar-agenda">Previstos por recorrência</h2></div><CalendarDays aria-hidden="true"/></div><p>Hoje no seu perfil: {civilDateLabel(query.data.today,locale)} · {query.data.timeZone}. Esta agenda mostra projeções; lançamentos já registrados continuam em Movimentos.</p>
        {!groups.size?<div className="finance-empty"><CalendarDays aria-hidden="true"/><h3>Nenhuma ocorrência prevista neste período.</h3><p>Cadastre uma recorrência ou consulte outro mês.</p></div>:<div className="calendar-agenda">{[...groups].map(([date,entries])=><section className="calendar-day" key={date}><h3><time dateTime={date}>{civilDateLabel(date,locale)}</time></h3><ul>{entries.map(entry=><li className={'calendar-entry '+entry.transactionType.toLowerCase()} key={entry.occurrenceKey}><div className="calendar-entry-icon">{entry.transactionType==='INCOME'?<ArrowDownLeft aria-hidden="true"/>:<ArrowUpRight aria-hidden="true"/>}</div><div className="calendar-entry-content"><strong>{entry.name}</strong><span>{recurrenceTypeLabels[entry.transactionType]} prevista · {recurrenceKindLabels[entry.recurrenceKind]}{entry.recurrenceKind==='SUBSCRIPTION'&&<Repeat2 aria-hidden="true"/>}</span>{entry.account&&<small>{entry.account.name}{entry.account.isActive?'':' · conta inativa'}</small>}{entry.category&&<small>{entry.category.name}{entry.category.isActive?'':' · categoria inativa'}</small>}</div><strong className="calendar-entry-amount">{formatMoney(entry.amountMinor,entry.currency,locale)}</strong></li>)}</ul></section>)}</div>}
      </section>
    </>}
  </div>;
}
