import { cloneElement, isValidElement, useId, useRef, useState, type ReactNode, type ComponentProps } from 'react';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Feedback } from '../../components/feedback';
import { FormSection } from '../../components/ui/form-section';
import { useServices } from '../../hooks/use-services';
import { useFinanceMutation } from './hooks';
import { formatMoney, parseMoney } from './money';
import { installmentPreview, requestKey } from './card-view';
import { validCivilDate } from './recurrence-view';
import { toInstant } from './dates';
import { currencyDigits, type CardInput, type CardView, type Category, type Account, type Currency, type PurchaseInput, type PaymentInput, type BillingRuleInput } from './contracts.generated';
function text(data: FormData, key: string) { return String(data.get(key) ?? ''); }
export function CardField({ label, children, ...props }: ComponentProps<'input'> & { label: string; children?: ReactNode }) {
  const labelId=useId();
  const control=isValidElement<{ 'aria-labelledby'?: string }>(children)?cloneElement(children,{ 'aria-labelledby':labelId }):children??<Input {...props} calendarLabel={label} aria-labelledby={labelId}/>;
  return <label className="card-field"><span id={labelId}>{label}</span>{control}</label>;
}
export function CardForm({ title, children, submit, button, onClose }: { title: string; children: ReactNode; submit: (data: FormData) => Promise<unknown>; button: string; onClose: () => void }) {
  const lock = useRef(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  return <section className="finance-panel"><h2>{title}</h2><form className="card-form" onSubmit={async e => { e.preventDefault(); if (lock.current) return; const data = new FormData(e.currentTarget); lock.current = true; setBusy(true); setError(''); try { await submit(data); onClose(); } catch (err) { setError((err as Error).message); } finally { lock.current = false; setBusy(false); } }}><fieldset disabled={busy}>{children}</fieldset><div className="ui-form-actions"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Fechar formulário</Button><Button type="submit" disabled={busy} aria-busy={busy}>{button}</Button></div><div className="card-form-feedback" aria-live="polite">{error && <Feedback>{error}</Feedback>}</div></form></section>;
}
export function CardEditor({ accounts, today, onClose }: { accounts: Account[]; today: string; onClose: () => void }) {
  const { finance } = useServices(), save = useFinanceMutation<CardInput>(i => finance.createCard(i)), [currency, setCurrency] = useState<Currency>('BRL'), [link, setLink] = useState(false);
  return <CardForm title="Novo cartão" button="Salvar cartão" onClose={onClose} submit={data => { const debt = parseMoney(text(data, 'debt') || '0', currency, false); if (BigInt(debt) < 0n) throw Error('Informe a dívida atual como valor positivo.'); return save.mutateAsync({ displayName: text(data, 'name').trim(), currency, ...(link ? { accountId: text(data, 'account') } : { initialDebtMinor: debt }), trackingStartDate: text(data, 'tracking'), closingDay: Number(text(data, 'closing')), dueDay: Number(text(data, 'due')), creditLimitMinor: text(data, 'limit').trim() ? parseMoney(text(data, 'limit'), currency) : null, issuerName: text(data, 'issuer').trim() || null, brand: text(data, 'brand').trim() || null, last4: text(data, 'last4').trim() || null }); }}>
    <FormSection title="Identificação do cartão"><CardField label="Nome do cartão" name="name" required maxLength={100} autoFocus /><CardField label="Moeda"><select className="finance-select" value={currency} onChange={e => setCurrency(e.target.value as Currency)}>{Object.keys(currencyDigits).map(c => <option key={c}>{c}</option>)}</select></CardField><CardField label="Emissor (opcional)" name="issuer" maxLength={100} /><CardField label="Bandeira (opcional)" name="brand" maxLength={100} /><CardField label="Últimos 4 dígitos (opcional)" name="last4" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} /></FormSection>
    <FormSection title="Conta e saldo inicial">
    <CardField label="Conta do cartão"><select className="finance-select" value={link ? 'link' : 'new'} onChange={e => setLink(e.target.value === 'link')}><option value="new">Criar conta credit</option><option value="link">Vincular conta credit existente</option></select></CardField>
    {link ? <CardField label="Conta credit existente"><select className="finance-select" name="account" required><option value="">Selecione</option>{accounts.filter(a => a.type === 'credit' && a.isActive && a.currency === currency).map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></CardField> : <CardField label="Dívida atual (valor positivo)" name="debt" inputMode="decimal" defaultValue="0" />}
    </FormSection><FormSection title="Acompanhamento, limite e ciclo"><CardField label="Início do acompanhamento" name="tracking" type="date" defaultValue={today} max={today} required /><CardField label="Limite do cartão (opcional)" name="limit" inputMode="decimal" /><CardField label="Dia de fechamento" name="closing" type="number" min={1} max={31} defaultValue={10} required /><CardField label="Dia de vencimento" name="due" type="number" min={1} max={31} defaultValue={17} required /></FormSection>
    <p className="card-form-note">Não informe número completo, CVV ou credenciais. Histórico anterior é legado, sem inventar faturas antigas. A conta vinculada não pode conter compras genéricas após o início escolhido.</p>
  </CardForm>;
}
export function PurchaseEditor({ view, categories, today, onClose }: { view: CardView; categories: Category[]; today: string; onClose: () => void }) {
  const { finance } = useServices(), save = useFinanceMutation<PurchaseInput>(i => finance.createCardPurchase(view.card.id, i)), key = useRef<{ signature: string; key: string } | null>(null), [total, setTotal] = useState(''), [count, setCount] = useState('1'), [date, setDate] = useState(today);
  let preview: ReturnType<typeof installmentPreview> = []; try { preview = installmentPreview(total, view.card.currency, Number(count), date, view.rules); } catch { /* Invalid draft has no financial effect. */ }
  return <CardForm title="Nova compra no cartão" button="Registrar compra" onClose={onClose} submit={data => { if (date > today || date < view.card.trackingStartDate || !validCivilDate(date)) throw Error('Informe uma data válida dentro do acompanhamento, até hoje.'); installmentPreview(total, view.card.currency, Number(count), date); const payload = { categoryId: text(data, 'category'), description: text(data, 'description').trim(), merchantName: text(data, 'merchant').trim() || null, purchaseDate: date, totalAmountMinor: parseMoney(total, view.card.currency), installmentCount: Number(count) }; key.current = requestKey(key.current, payload); return save.mutateAsync({ ...payload, idempotencyKey: key.current.key }); }}>
    <FormSection title="Dados da compra"><CardField label="Descrição da compra" name="description" required maxLength={400} autoFocus /><CardField label="Estabelecimento (opcional)" name="merchant" maxLength={100} /><CardField label="Categoria de despesa"><select className="finance-select" name="category" required><option value="">Selecione</option>{categories.filter(c => c.kind === 'EXPENSE' && c.isActive).map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select></CardField><CardField label="Data da compra" type="date" value={date} onChange={e => setDate(e.target.value)} min={view.card.trackingStartDate} max={today} required /></FormSection><FormSection title="Valor e parcelamento"><CardField label={'Valor total (' + view.card.currency + ')'} inputMode="decimal" value={total} onChange={e => setTotal(e.target.value)} required /><CardField label="Quantidade de parcelas" type="number" min={1} max={60} value={count} onChange={e => setCount(e.target.value)} required /></FormSection>
    <div className="card-preview card-form-note" aria-label="Prévia das parcelas"><h3>Prévia — datas previstas, cálculo final no servidor</h3>{preview.length ? <ol>{preview.map(p => <li key={p.installmentNumber}>{p.installmentNumber}/{count} · {formatMoney(p.amountMinor, view.card.currency)} · {p.scheduledDate}{p.dueDate && ' · Vencimento ' + p.dueDate}</li>)}</ol> : <p>Informe total, data e quantidade para visualizar as parcelas.</p>}</div><p className="card-form-note">Cada parcela é uma despesa. Parcelas futuras são compromissos, não saldo real atual nem patrimônio atual.</p>
  </CardForm>;
}
export function PaymentEditor({ view, accounts, today, onClose }: { view: CardView; accounts: Account[]; today: string; onClose: () => void }) {
  const paymentTime = useRef<{ date: string; instant: string } | null>(null);
  const { finance } = useServices(), save = useFinanceMutation<PaymentInput>(i => finance.payCard(view.card.id, i)), key = useRef<{ signature: string; key: string } | null>(null), outstanding = BigInt(view.legacyOutstandingMinor) + view.invoices.reduce((sum, i) => sum + BigInt(i.outstandingMinor), 0n), digits = currencyDigits[view.card.currency], initial = String(outstanding / 10n ** BigInt(digits)) + (digits ? '.' + String(outstanding % 10n ** BigInt(digits)).padStart(digits, '0') : '');
  return <CardForm title="Pagar fatura" button="Registrar pagamento" onClose={onClose} submit={async data => { const date = text(data, 'date'); if (!validCivilDate(date)) throw Error('Informe uma data válida.'); const source = text(data, 'source'), amountMinor = parseMoney(text(data, 'amount'), view.card.currency); // Local noon maps the selected date; backend receives an explicit instant.
    if (paymentTime.current?.date !== date) paymentTime.current = { date, instant: date === today ? new Date().toISOString() : toInstant(date + 'T12:00', view.timeZone) };
    const payload = { sourceAccountId: source, amountMinor, occurredAt: paymentTime.current.instant }; key.current = requestKey(key.current, payload); return save.mutateAsync({ ...payload, idempotencyKey: key.current.key }); }}>
    <CardField label="Conta de origem"><select className="finance-select" name="source" required><option value="">Selecione</option>{accounts.filter(a => a.isActive && a.currency === view.card.currency && a.type !== 'credit' && a.type !== 'debt' && a.id !== view.card.accountId).map(a => <option value={a.id} key={a.id}>{a.name}</option>)}</select></CardField><CardField label="Valor do pagamento" name="amount" inputMode="decimal" defaultValue={initial} required /><CardField label="Data do pagamento" name="date" type="date" defaultValue={today} min={view.card.trackingStartDate} max={today} required /><p className="card-form-note">Pagamento será registrado como transferência, não como nova despesa. Pagamentos parciais e créditos excedentes são permitidos, sem cálculo de juros.</p>
  </CardForm>;
}
export function RuleEditor({ view, today, onClose }: { view: CardView; today: string; onClose: () => void }) {
  const { finance } = useServices(), save = useFinanceMutation<BillingRuleInput>(i => finance.addCardRule(view.card.id, i)), last = view.rules.at(-1)!;
  return <CardForm title="Nova versão de fechamento e vencimento" button="Salvar nova regra" onClose={onClose} submit={data => { const effectiveFrom = text(data, 'from'); if (!validCivilDate(effectiveFrom) || effectiveFrom < today || effectiveFrom <= last.effectiveFrom) throw Error('Use uma data de hoje ou futura, posterior à última versão.'); return save.mutateAsync({ effectiveFrom, closingDay: Number(text(data, 'closing')), dueDay: Number(text(data, 'due')) }); }}><CardField label="Vigência da nova regra" name="from" type="date" min={today} required /><CardField label="Novo dia de fechamento" name="closing" type="number" min={1} max={31} defaultValue={last.closingDay} required /><CardField label="Novo dia de vencimento" name="due" type="number" min={1} max={31} defaultValue={last.dueDay} required /><p className="card-form-note">Cria uma versão; faturas já fechadas não mudam. Parcelas futuras usam a regra vigente na data da parcela.</p></CardForm>;
}
