import { useRef, useState } from 'react';
import { CardField as Field, CardForm as Form } from './card-forms';
import { FormSection } from '../../components/ui/form-section';
import { Button } from '../../components/ui/button';
import { useServices } from '../../hooks/use-services';
import { useFinanceMutation } from './hooks';
import { useNetWorthItems } from './net-worth-hooks';
import { currencyDigits, type Account, type Category, type Currency, type DebtInput, type DebtPatch, type DebtPaymentInput, type DebtTermInput, type DebtView } from './contracts.generated';
import { formatMoney, parseMoney } from './money';
import { debtTypes, paymentPreview, percentToRate, rateToPercent } from './debt-view';
import { requestKey } from './card-view';
import { validCivilDate } from './recurrence-view';
import { toInstant } from './dates';
const text=(data:FormData,key:string)=>String(data.get(key)??'');
function TermFields({view}:{view?:DebtView}){const last=view?.terms.at(-1);return <><Field label="Taxa efetiva (%)" name="rate" inputMode="decimal" defaultValue={last?rateToPercent(last.rate):'12'} required/><Field label="Período da taxa"><select className="finance-select" name="period" defaultValue={last?.ratePeriod??'EFFECTIVE_ANNUAL'}><option value="EFFECTIVE_ANNUAL">Efetiva anual</option><option value="EFFECTIVE_MONTHLY">Efetiva mensal</option></select></Field><Field label="Pagamento mínimo declarado" name="minimum" inputMode="decimal" defaultValue={last?decimalAmount(last.minimumPaymentMinor,view!.debt.currency):'500'} required/><Field label="Dia de vencimento" name="due" type="number" min={1} max={31} defaultValue={last?.dueDay??10} required/><p className="card-form-note">12 significa 12%. Use uma taxa efetiva fixa; taxas indexadas não são suportadas. O mínimo é informado por você, não calculado pelo banco. Dia 31 é ajustado ao último dia de cada mês.</p></>;}
function decimalAmount(minor:string,currency:Currency){const digits=currencyDigits[currency],factor=10n**BigInt(digits),value=BigInt(minor);return String(value/factor)+(digits?'.'+String(value%factor).padStart(digits,'0'):'');}
function terms(data:FormData,currency:Currency){return {rate:percentToRate(text(data,'rate')),ratePeriod:text(data,'period') as DebtTermInput['ratePeriod'],minimumPaymentMinor:parseMoney(text(data,'minimum'),currency),dueDay:Number(text(data,'due'))};}
export function DebtEditor({today,onClose}:{today:string;onClose:()=>void}){
  const {finance}=useServices(),save=useFinanceMutation<DebtInput>(i=>finance.createDebt(i)),[currency,setCurrency]=useState<Currency>('BRL'),manual=useNetWorthItems({kind:'LIABILITY',status:'ACTIVE',currency});
  const items=manual.data?.pages.flatMap(p=>p.items)??[];
  return <Form title="Nova dívida" button="Salvar dívida" onClose={onClose} submit={data=>{const principal=parseMoney(text(data,'principal'),currency,false),tracking=text(data,'tracking');if(BigInt(principal)<0n||!validCivilDate(tracking)||tracking>today)throw Error('Informe principal positivo ou zero e início válido até hoje.');const manualId=text(data,'manual');return save.mutateAsync({name:text(data,'name').trim(),lender:text(data,'lender').trim()||null,debtType:text(data,'type') as DebtInput['debtType'],currency,initialPrincipalMinor:principal,trackingStartDate:tracking,...terms(data,currency),...(manualId?{manualNetWorthItemId:manualId}:{})});}}>
    <FormSection title="Identificação da dívida"><Field label="Nome da dívida" name="name" required maxLength={100} autoFocus/><Field label="Credor (opcional)" name="lender" maxLength={100}/><Field label="Tipo de dívida"><select className="finance-select" name="type">{Object.entries(debtTypes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Moeda"><select className="finance-select" value={currency} onChange={e=>setCurrency(e.target.value as Currency)}>{Object.keys(currencyDigits).map(c=><option key={c}>{c}</option>)}</select></Field></FormSection>
    <FormSection title="Principal e acompanhamento"><Field label="Principal atual (valor positivo)" name="principal" inputMode="decimal" required/><Field label="Início do acompanhamento" name="tracking" type="date" defaultValue={today} max={today} required/></FormSection><FormSection title="Condições de pagamento"><TermFields/></FormSection>
    <FormSection title="Vínculo patrimonial opcional"><Field label="Converter passivo manual (opcional)"><select className="finance-select" name="manual" key={currency} disabled={manual.isPending||manual.isError}><option value="">Criar sem conversão</option>{items.map(i=><option key={i.id} value={i.id}>{i.name} · {i.latestValuation?formatMoney(i.latestValuation.valueMinor,currency):'Sem avaliação'}</option>)}</select></Field>{manual.hasNextPage&&<Button variant="outline" type="button" onClick={()=>void manual.fetchNextPage()}>Carregar mais passivos</Button>}</FormSection><p className="card-form-note">A conta debt terá saldo inicial negativo. Na conversão explícita, o passivo manual só é arquivado se proprietário, moeda e última avaliação coincidirem exatamente com o principal. Nenhuma dívida é detectada automaticamente.</p>
  </Form>;
}
export function DebtMetadataEditor({view,onClose}:{view:DebtView;onClose:()=>void}){const {finance}=useServices(),save=useFinanceMutation<DebtPatch>(i=>finance.patchDebt(view.debt.id,i));return <Form title="Editar dados da dívida" button="Salvar dados" onClose={onClose} submit={data=>save.mutateAsync({name:text(data,'name').trim(),lender:text(data,'lender').trim()||null,debtType:text(data,'type') as DebtPatch['debtType']})}><Field label="Nome da dívida" name="name" required defaultValue={view.debt.name} maxLength={100} autoFocus/><Field label="Credor (opcional)" name="lender" defaultValue={view.debt.lender??''} maxLength={100}/><Field label="Tipo de dívida"><select className="finance-select" name="type" defaultValue={view.debt.debtType}>{Object.entries(debtTypes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><p className="card-form-note">Principal e histórico não são editáveis. Corrija pagamentos pela ação controlada no histórico.</p></Form>;}
export function DebtTermEditor({view,onClose}:{view:DebtView;onClose:()=>void}){const {finance}=useServices(),save=useFinanceMutation<DebtTermInput>(i=>finance.addDebtTerm(view.debt.id,i));return <Form title="Nova versão dos termos" button="Salvar nova versão" onClose={onClose} submit={data=>{const effectiveFrom=text(data,'from');if(!validCivilDate(effectiveFrom)||effectiveFrom<=view.asOf||effectiveFrom<=view.terms.at(-1)!.effectiveFrom)throw Error('Use uma data futura, posterior à última versão.');return save.mutateAsync({...terms(data,view.debt.currency),effectiveFrom});}}><Field label="Vigência da nova taxa" name="from" type="date" required autoFocus/><TermFields view={view}/><p className="card-form-note">A nova versão fecha a anterior sem alterar seu histórico. Simulações usam os termos vigentes na data prevista de vencimento.</p></Form>;}
export function DebtPaymentEditor({view,accounts,categories,onClose}:{view:DebtView;accounts:Account[];categories:Category[];onClose:()=>void}){
  const {finance}=useServices(),save=useFinanceMutation<DebtPaymentInput>(i=>finance.payDebt(view.debt.id,i)),key=useRef<{signature:string;key:string}|null>(null),instant=useRef<{date:string;value:string}|null>(null),[principal,setPrincipal]=useState(''),[interest,setInterest]=useState('0'),[fee,setFee]=useState('0'),currency=view.debt.currency;
  let preview:ReturnType<typeof paymentPreview>|null=null;try{preview=paymentPreview(principal,interest,fee,view.outstandingPrincipalMinor,currency);}catch{/* Draft is never an actual payment. */}
  const options=categories.filter(c=>c.isActive&&c.kind==='EXPENSE');
  return <Form title="Registrar pagamento real" button="Registrar pagamento" onClose={onClose} submit={data=>{const p=paymentPreview(principal,interest,fee,view.outstandingPrincipalMinor,currency),date=text(data,'date');if(p.totalMinor==='0')throw Error('Informe um pagamento maior que zero.');if(!validCivilDate(date)||date>view.asOf||date<view.debt.trackingStartDate)throw Error('Informe uma data válida dentro do acompanhamento, até hoje.');if(instant.current?.date!==date)instant.current={date,value:date===view.asOf?new Date().toISOString():toInstant(date+'T12:00',view.timeZone)};const ic=text(data,'interestCategory'),fc=text(data,'feeCategory'),payload={sourceAccountId:text(data,'source'),principalAmountMinor:parseMoney(principal||'0',currency,false),interestAmountMinor:parseMoney(interest||'0',currency,false),feeAmountMinor:parseMoney(fee||'0',currency,false),paidAt:instant.current.value,...(ic&&BigInt(parseMoney(interest||'0',currency,false))>0n?{interestCategoryId:ic}:{}),...(fc&&BigInt(parseMoney(fee||'0',currency,false))>0n?{feeCategoryId:fc}:{})};key.current=requestKey(key.current,payload);return save.mutateAsync({...payload,idempotencyKey:key.current.key});}}>
    <FormSection title="Origem e data"><Field label="Conta de origem"><select className="finance-select" name="source" required autoFocus><option value="">Selecione</option>{accounts.filter(a=>a.isActive&&a.currency===currency&&['checking','savings','cash','other'].includes(a.type)).map(a=><option key={a.id} value={a.id}>{a.name} · {formatMoney(a.balanceMinor,currency)}</option>)}</select></Field><Field label="Data do pagamento" name="date" type="date" defaultValue={view.asOf} min={view.debt.trackingStartDate} max={view.asOf} required/></FormSection><FormSection title="Valores pagos"><Field label={'Principal pago ('+currency+')'} inputMode="decimal" value={principal} onChange={e=>setPrincipal(e.target.value)}/><Field label={'Juros pagos ('+currency+')'} inputMode="decimal" value={interest} onChange={e=>setInterest(e.target.value)}/><Field label={'Tarifas pagas ('+currency+')'} inputMode="decimal" value={fee} onChange={e=>setFee(e.target.value)}/></FormSection><FormSection title="Classificação dos custos"><Field label="Categoria dos juros (opcional)"><select className="finance-select" name="interestCategory"><option value="">Sem categoria</option>{options.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Categoria das tarifas (opcional)"><select className="finance-select" name="feeCategory"><option value="">Sem categoria</option>{options.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>
    </FormSection><div className="debt-payment-preview card-form-note" aria-live="polite"><p>Total debitado: {preview?formatMoney(preview.totalMinor,currency):'Revise os valores'}</p><p>Principal restante: {preview?formatMoney(preview.remainingMinor,currency):'Revise os valores'}</p></div><p className="card-form-note">Somente principal reduz o saldo devedor. Principal é transferência; juros e tarifas são despesas. A conta de origem deve ter saldo disponível para o total.</p>
  </Form>;
}
