import { useState } from 'react';
import { Dialog } from '../../components/ui/dialog';
import { Button } from '../../components/ui/button';
import { Feedback } from '../../components/feedback';
import { useServices } from '../../hooks/use-services';
import { useFinanceMutation } from './hooks';
import { useNetWorth,useNetWorthHistory,useNetWorthItems,useNetWorthValuations } from './net-worth-hooks';
import { NetWorthEditor } from './net-worth-form';
import { chartCoordinates,historyStart,netWorthLabels } from './net-worth-view';
import { formatMoney } from './money';
import type { Currency,NetWorthItem,NetWorthStatus,NetWorthHistory } from './contracts.generated';
import { currencyDigits } from './contracts.generated';
function Evolution({data}:{data:NetWorthHistory}) {const points=chartCoordinates(data.points.map(p=>p.netWorthMinor));return <section className="finance-panel"><h2>Evolução patrimonial</h2><p>Últimos 12 meses · {data.currency}. Sem projeções futuras.</p><svg className="net-worth-chart" viewBox="0 0 100 100" role="img" aria-label="Evolução do patrimônio líquido; valores exatos disponíveis na tabela abaixo" preserveAspectRatio="none"><polyline points={points.map(p=>p.x+','+p.y).join(' ')} fill="none" stroke="currentColor" strokeWidth="1"/>{points.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="1.5"><title>{data.points[i]!.asOf+' · Ativos '+formatMoney(data.points[i]!.totalAssetsMinor,data.currency)+' · Passivos '+formatMoney(data.points[i]!.totalLiabilitiesMinor,data.currency)+' · Patrimônio '+formatMoney(data.points[i]!.netWorthMinor,data.currency)}</title></circle>)}</svg><div className="net-worth-table" role="region" aria-label="Tabela financeira" tabIndex={0}><table><caption>Posição mensal em {data.currency}</caption><thead><tr><th scope="col">Data</th><th scope="col">Ativos</th><th scope="col">Passivos</th><th scope="col">Patrimônio líquido</th></tr></thead><tbody>{data.points.map(p=><tr key={p.asOf}><th scope="row"><time dateTime={p.asOf}>{p.asOf}</time></th><td>{formatMoney(p.totalAssetsMinor,data.currency)}</td><td>{formatMoney(p.totalLiabilitiesMinor,data.currency)}</td><td>{formatMoney(p.netWorthMinor,data.currency)}</td></tr>)}</tbody></table></div></section>;}
function ValuationHistory({item,onClose}:{item:NetWorthItem;onClose:()=>void}) {const query=useNetWorthValuations(item.id);return <section className="finance-panel"><h2>Histórico de avaliações — {item.name}</h2><p>Valor atual conforme avaliação mais recente.</p>{query.isPending?<p role="status">Carregando avaliações…</p>:query.isError?<Feedback><p>Não foi possível carregar o histórico.</p><Button onClick={()=>void query.refetch()}>Tentar novamente</Button></Feedback>:<><ul className="finance-list">{query.data.pages.flatMap(p=>p.items).map(v=><li key={v.id}><time dateTime={v.valuationDate}>{v.valuationDate}</time><strong>{formatMoney(v.valueMinor,item.currency)}</strong><p>{v.note??'Sem nota'}</p></li>)}</ul>{query.hasNextPage&&<Button disabled={query.isFetchingNextPage} onClick={()=>void query.fetchNextPage()}>Mais avaliações</Button>}</>}<Button variant="outline" onClick={onClose}>Fechar histórico</Button></section>;}
export function NetWorthPage() {
 const {finance}=useServices(),[currency,setCurrency]=useState<Currency>('BRL'),[asOf,setAsOf]=useState(''),[status,setStatus]=useState<NetWorthStatus>('ACTIVE'),[editor,setEditor]=useState<{item:NetWorthItem|null;mode:'create'|'edit'|'valuation'}|null>(null),[historyItem,setHistoryItem]=useState<NetWorthItem|null>(null),[archiveItem,setArchiveItem]=useState<NetWorthItem|null>(null);
 const summary=useNetWorth(asOf||undefined),items=useNetWorthItems({currency,status}),date=summary.data?.asOf??'',month=date.slice(0,7),history=useNetWorthHistory({currency,from:month?historyStart(month):'2026-01',to:month||'2026-01'},!!date);
 const archive=useFinanceMutation<string>(id=>finance.archiveNetWorthItem(id));
 const total=summary.data?.totals.find(t=>t.currency===currency),rows=items.data?.pages.flatMap(p=>p.items)??[];
 return <div className="net-worth-page"><div className="page-intro"><p className="eyebrow">CLAREZA PATRIMONIAL</p><h1 tabIndex={-1}>Patrimônio</h1><p>Contas reais e bens ou dívidas externos, sem duplicação e sem misturar moedas.</p></div>
 <div className="finance-actions"><label>Moeda do patrimônio <select className="finance-select" value={currency} onChange={e=>setCurrency(e.target.value as Currency)}>{Object.keys(currencyDigits).map(c=><option key={c}>{c}</option>)}</select></label><label>Data de referência <input className="finance-select" type="date" value={asOf} onChange={e=>setAsOf(e.target.value)}/></label><Button onClick={()=>setEditor({item:null,mode:'create'})} disabled={!date}>Novo item</Button></div>
 {summary.isPending?<p role="status">Carregando patrimônio…</p>:summary.isError?<Feedback><p>Não foi possível carregar o patrimônio.</p><Button onClick={()=>void summary.refetch()}>Tentar novamente</Button></Feedback>:<><p>Posição ao fim de {summary.data.asOf} · {summary.data.timezone}</p><div className="net-worth-metrics">{[['Patrimônio líquido',total?.netWorthMinor],['Ativos',total?.totalAssetsMinor],['Passivos',total?.totalLiabilitiesMinor]].map(([label,value])=><section className="finance-panel" key={label}><h2>{label}</h2><strong className="net-worth-value">{formatMoney(value??'0',currency)}</strong></section>)}</div><section className="finance-panel"><h2>Composição — {currency}</h2><p>Contas: {formatMoney(total?.accountNetMinor??'0',currency)} · Bens/ativos: {formatMoney(total?.manualAssetsMinor??'0',currency)} · Passivos externos: {formatMoney(total?.manualLiabilitiesMinor??'0',currency)}</p><ul className="finance-list">{summary.data.components.filter(c=>c.currency===currency).map(c=><li key={c.source+c.id}><span>{c.name} · {c.source==='ACCOUNT'?'Conta'+(c.isActive?'':' inativa'):c.kind==='ASSET'?'Ativo externo':'Passivo externo'}</span><strong>{formatMoney(c.signedValueMinor,currency)}</strong></li>)}</ul><p>Saldos das contas são somente leitura. Use o Finance Core para corrigir movimentos. O saldo inicial participa a partir da criação da conta.</p></section></>}
 {history.isPending&&date?<p role="status">Carregando evolução…</p>:history.isError?<Feedback><p>Não foi possível carregar a evolução.</p><Button onClick={()=>void history.refetch()}>Tentar novamente</Button></Feedback>:history.data?<Evolution data={history.data}/>:null}
 {editor&&<NetWorthEditor {...editor} today={summary.data?new Intl.DateTimeFormat('en-CA',{timeZone:summary.data.timezone}).format(new Date()):date} onClose={()=>setEditor(null)}/>}
 <section className="finance-panel"><h2>Itens externos</h2><p>Evite cadastrar novamente valores que já estejam representados em suas contas.</p><label>Status dos itens <select className="finance-select" value={status} onChange={e=>setStatus(e.target.value as NetWorthStatus)}><option value="ACTIVE">Ativos</option><option value="ARCHIVED">Arquivados</option></select></label>{items.isPending?<p role="status">Carregando itens…</p>:items.isError?<Feedback><p>Não foi possível carregar os itens.</p><Button onClick={()=>void items.refetch()}>Tentar novamente</Button></Feedback>:rows.length===0?<p>Adicione bens ou dívidas que ainda não estão representados nas suas contas.</p>:<ul className="finance-list">{rows.map(item=><li key={item.id}><div><h3>{item.name}</h3><p>{item.kind==='ASSET'?'Ativo externo':'Passivo'} · {netWorthLabels[item.category]} · {item.currency} · {item.status==='ARCHIVED'?'Arquivado':'Ativo'}</p><strong>{formatMoney(item.latestValuation?.valueMinor??'0',item.currency)}</strong><p>Última avaliação: {item.latestValuation?.valuationDate??'Sem avaliação'}</p></div><div className="finance-actions"><Button variant="outline" onClick={()=>setHistoryItem(item)}>Ver histórico</Button>{item.status==='ACTIVE'&&<><Button variant="outline" onClick={()=>setEditor({item,mode:'edit'})}>Editar dados</Button><Button onClick={()=>setEditor({item,mode:'valuation'})}>Nova avaliação</Button><Button variant="outline" onClick={()=>setArchiveItem(item)}>Arquivar</Button></>}</div></li>)}</ul>}{items.hasNextPage&&<Button disabled={items.isFetchingNextPage} onClick={()=>void items.fetchNextPage()}>Mais itens</Button>}</section>
 {historyItem&&<ValuationHistory item={historyItem} onClose={()=>setHistoryItem(null)}/>}
 {archiveItem&&<Dialog role="alertdialog" title={'Arquivar ' + archiveItem.name + '?'} onClose={() => setArchiveItem(null)} pending={archive.isPending}><p>O histórico será preservado. O item sai da posição atual e não poderá receber avaliações nem ser restaurado.</p>{archive.isError&&<Feedback>{(archive.error as Error).message}</Feedback>}<div className="finance-actions"><Button disabled={archive.isPending} onClick={async()=>{try{await archive.mutateAsync(archiveItem.id);setArchiveItem(null);}catch{/* Feedback above. */}}}>Confirmar arquivamento</Button><Button disabled={archive.isPending} variant="outline" onClick={()=>setArchiveItem(null)}>Cancelar arquivamento</Button></div></Dialog>}
 </div>;
}
