import { useState } from 'react';
import { Link, useSearchParams } from 'react-router';
import { Archive, PauseCircle, PlayCircle, Repeat2 } from 'lucide-react';
import { Button } from '../../components/ui/button';
import { Feedback } from '../../components/feedback';
import { useServices } from '../../hooks/use-services';
import { useMe } from '../../profile/hooks';
import { useAccounts, useCategories, useFinanceMutation } from './hooks';
import { useRecurrences, useSubscriptionRadar } from './recurrence-hooks';
import { RecurrenceEditor } from './recurrence-form';
import { RecurrenceQuerySchema, currencyDigits } from './contracts.generated';
import type { Recurrence, RecurrenceQuery, Currency } from './contracts.generated';
import { civilDateLabel, frequencyLabels, recurrenceKindLabels, recurrencePeriod, recurrenceStatusLabels, recurrenceTypeLabels } from './recurrence-view';
import { formatMoney } from './money';
export function RecurrenceNotice() { return <p className="goal-planning-note">Recorrências são expectativas financeiras. Elas não criam lançamentos nem alteram contas, transações, transferências, orçamentos ou metas. Assinaturas são cadastradas por você.</p>; }
function SubscriptionRadarPanel({currency,locale}:{currency?:Currency;locale:string}) {
  const query=useSubscriptionRadar(currency?{currency}:{}),[shown,setShown]=useState(8);
  return <section className="finance-panel subscription-radar" aria-labelledby="subscription-radar-title"><div className="recurrence-section-heading"><div><p className="finance-eyebrow">PRÓXIMOS 30 DIAS</p><h2 id="subscription-radar-title">Radar de assinaturas</h2></div><Repeat2 aria-hidden="true"/></div>
    {query.isPending?<p role="status">Carregando assinaturas…</p>:query.isError?<><Feedback>Não foi possível carregar o radar de assinaturas.</Feedback><Button variant="outline" aria-label="Tentar novamente radar" onClick={()=>void query.refetch()}>Tentar novamente</Button></>:query.data&&<>
      <p>Valores previstos pela recorrência cadastrada, a partir de {civilDateLabel(query.data.from,locale)}. Não são gastos confirmados.</p>
      {!query.data.subscriptions.length?<p>Nenhuma assinatura ativa.</p>:<><div className="finance-summary-grid">{query.data.totals.map(t=><div className="recurrence-radar-total" key={t.currency}><p>{t.currency} · {t.subscriptionCount} {t.subscriptionCount===1?'assinatura ativa':'assinaturas ativas'}</p><strong>{formatMoney(t.amountMinor,t.currency,locale)}</strong><span>{t.occurrenceCount} {t.occurrenceCount===1?'cobrança prevista':'cobranças previstas'} em 30 dias</span></div>)}</div>
      <details className="recurrence-active-subscriptions"><summary>Assinaturas ativas ({query.data.subscriptions.length})</summary><ul>{query.data.subscriptions.map(s=><li key={s.id}><strong>{s.name}</strong><span>{recurrencePeriod(s)} · {formatMoney(s.amountMinor,s.currency,locale)}</span><span>Próxima: {civilDateLabel(s.nextOccurrenceDate,locale)}</span>{s.account&&<span>{s.account.name}{s.account.isActive?'':' · conta inativa'}</span>}{s.category&&<span>{s.category.name}{s.category.isActive?'':' · categoria inativa'}</span>}</li>)}</ul></details>
      <h3>Próximas cobranças previstas</h3>{!query.data.entries.length?<p>Nenhuma cobrança prevista nesta janela.</p>:<><ul className="radar-charges">{query.data.entries.slice(0,shown).map(e=><li key={e.occurrenceKey}><time dateTime={e.date}>{civilDateLabel(e.date,locale)}</time><span>{e.name}</span><strong>{formatMoney(e.amountMinor,e.currency,locale)}</strong></li>)}</ul>{shown<query.data.entries.length&&<Button variant="outline" onClick={()=>setShown(n=>n+8)}>Mostrar mais cobranças</Button>}</>}</>}
    </>}
  </section>;
}
export function RecurrencesPage() {
  const [params,setParams]=useSearchParams(),[creating,setCreating]=useState(false),[editing,setEditing]=useState<Recurrence|null>(null),[confirmArchive,setConfirmArchive]=useState<string|null>(null),[message,setMessage]=useState('');
  const candidate=Object.fromEntries(['status','transactionType','recurrenceKind','currency','accountId','categoryId'].map(key=>[key,params.get(key)]).filter(([,value])=>value));
  const parsed=RecurrenceQuerySchema.safeParse(candidate),filters:RecurrenceQuery=parsed.success?parsed.data:{};
  const query=useRecurrences(filters),accounts=useAccounts(),categories=useCategories(),me=useMe(),{finance}=useServices(),locale=me.data?.profile?.locale??'pt-BR';
  const mutation=useFinanceMutation<{id:string;action:'pause'|'resume'|'archive'}>(v=>finance.recurrenceStatus(v.id,v.action));
  const rows=query.data?.pages.flatMap(p=>p.items)??[];
  const update=(key:string,value:string)=>{const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);setParams(next);setEditing(null);setCreating(false);};
  const status=async(id:string,action:'pause'|'resume'|'archive')=>{try{await mutation.mutateAsync({id,action});setConfirmArchive(null);setMessage(action==='pause'?'Recorrência pausada.':action==='resume'?'Recorrência retomada.':'Recorrência arquivada.');}catch{/* Safe API feedback below. */}};
  const options=(labels:Record<string,string>)=>Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>);
  return <div className="finance-page recurrence-page"><header className="finance-page-heading"><div><p className="finance-eyebrow">FINANCE · PLANEJAMENTO</p><h1 tabIndex={-1}>Recorrências e assinaturas</h1><p>Organize receitas e despesas que se repetem e acompanhe seus próximos compromissos.</p></div><div className="finance-actions"><Button variant="outline" asChild><Link to="/finance/calendar">Ver calendário</Link></Button><Button onClick={()=>{setCreating(true);setEditing(null);setMessage('');}} disabled={accounts.isPending||categories.isPending||accounts.isError||categories.isError}>Nova recorrência</Button></div></header>
    <RecurrenceNotice/>{message&&<Feedback success>{message}</Feedback>}
    {(accounts.isError||categories.isError)&&<div><Feedback>Não foi possível carregar contas e categorias para o cadastro.</Feedback><Button variant="outline" onClick={()=>{void accounts.refetch();void categories.refetch();}}>Tentar novamente associações</Button></div>}
    {(creating||editing)&&<RecurrenceEditor key={editing?.id??'new'} row={editing} accounts={accounts.data??[]} categories={categories.data??[]} onCancel={()=>{setCreating(false);setEditing(null);}} onSaved={()=>{setCreating(false);setEditing(null);setMessage(editing?'Recorrência atualizada.':'Recorrência cadastrada.');if(!editing)setParams({});}}/>}
    <SubscriptionRadarPanel {...(filters.currency?{currency:filters.currency}:{})} locale={locale}/>
    <section className="finance-panel"><div className="recurrence-section-heading"><h2>Suas recorrências</h2><span>{rows.length} exibidas</span></div><div className="recurrence-filters">
      <label>Status<select className="finance-select" aria-label="Status das recorrências" value={filters.status??''} onChange={e=>update('status',e.target.value)}><option value="">Todos os status</option>{options(recurrenceStatusLabels)}</select></label>
      <label>Tipo<select className="finance-select" aria-label="Tipo das recorrências" value={filters.transactionType??''} onChange={e=>update('transactionType',e.target.value)}><option value="">Receitas e despesas</option>{options(recurrenceTypeLabels)}</select></label>
      <label>Classificação<select className="finance-select" aria-label="Classificação das recorrências" value={filters.recurrenceKind??''} onChange={e=>update('recurrenceKind',e.target.value)}><option value="">Todas as classificações</option>{options(recurrenceKindLabels)}</select></label>
      <label>Moeda<select className="finance-select" aria-label="Moeda das recorrências" value={filters.currency??''} onChange={e=>update('currency',e.target.value)}><option value="">Todas as moedas</option>{Object.keys(currencyDigits).map(c=><option key={c}>{c}</option>)}</select></label>
      <label>Conta<select className="finance-select" aria-label="Filtrar conta" value={filters.accountId??''} onChange={e=>update('accountId',e.target.value)}><option value="">Todas as contas</option>{accounts.data?.map(a=><option value={a.id} key={a.id}>{a.name}{a.isActive?'':' · inativa'}</option>)}</select></label>
      <label>Categoria<select className="finance-select" aria-label="Filtrar categoria" value={filters.categoryId??''} onChange={e=>update('categoryId',e.target.value)}><option value="">Todas as categorias</option>{categories.data?.map(c=><option value={c.id} key={c.id}>{c.name}{c.isActive?'':' · inativa'}</option>)}</select></label>
    </div>{mutation.isError&&<Feedback>{mutation.error.message}</Feedback>}
    {query.isPending?<p role="status">Carregando recorrências…</p>:query.isError?<><Feedback>Não foi possível carregar suas recorrências.</Feedback><Button variant="outline" aria-label="Tentar novamente recorrências" onClick={()=>void query.refetch()}>Tentar novamente</Button></>:!rows.length?<div className="finance-empty"><Repeat2 aria-hidden="true"/><h3>{Object.keys(filters).length?'Nenhuma recorrência corresponde aos filtros.':'Cadastre sua primeira recorrência'}</h3><p>Cadastre despesas e receitas que se repetem para visualizar os próximos compromissos.</p></div>:<div className="recurrence-list">{rows.map(row=><article className="recurrence-row" key={row.id}><div className="recurrence-row-heading"><div><p className="finance-eyebrow">{recurrenceTypeLabels[row.transactionType]} · {recurrenceKindLabels[row.recurrenceKind]}</p><h3>{row.name}</h3>{row.description&&<p>{row.description}</p>}</div><span className="goal-status-label">{row.status==='ACTIVE'?<PlayCircle aria-hidden="true"/>:row.status==='PAUSED'?<PauseCircle aria-hidden="true"/>:<Archive aria-hidden="true"/>}{recurrenceStatusLabels[row.status]}</span></div>
      <dl className="recurrence-metrics"><div><dt>Valor previsto</dt><dd>{formatMoney(row.amountMinor,row.currency,locale)}</dd></div><div><dt>Periodicidade</dt><dd>{frequencyLabels[row.frequency]}{row.intervalCount>1&&<small>{recurrencePeriod(row)}</small>}</dd></div><div><dt>Próxima ocorrência</dt><dd>{civilDateLabel(row.nextOccurrenceDate,locale)}</dd></div><div><dt>Vigência</dt><dd>{civilDateLabel(row.startDate,locale)}{row.endDate?' a '+civilDateLabel(row.endDate,locale):' · sem data final'}</dd></div></dl>
      <p className="recurrence-associations">Conta: {row.account?row.account.name+(row.account.isActive?'':' · inativa'):'Sem vínculo'} · Categoria: {row.category?row.category.name+(row.category.isActive?'':' · inativa'):'Sem vínculo'}</p>
      {row.status!=='ARCHIVED'&&<div className="finance-actions"><Button variant="outline" onClick={()=>{setEditing(row);setCreating(false);setMessage('');}} disabled={mutation.isPending||accounts.isPending||categories.isPending||accounts.isError||categories.isError}>Editar {row.name}</Button><Button variant="outline" onClick={()=>void status(row.id,row.status==='PAUSED'?'resume':'pause')} disabled={mutation.isPending}>{row.status==='PAUSED'?'Retomar':'Pausar'}</Button><Button variant="outline" onClick={()=>setConfirmArchive(row.id)} disabled={mutation.isPending}>Arquivar</Button></div>}
      {confirmArchive===row.id&&<div className="recurrence-archive-confirm" role="group" aria-label={'Confirmar arquivamento de '+row.name}><p>Arquivar encerra esta regra e preserva o cadastro. Ela não poderá ser retomada.</p><Button onClick={()=>void status(row.id,'archive')} disabled={mutation.isPending}>Confirmar arquivamento</Button><Button variant="outline" onClick={()=>setConfirmArchive(null)}>Cancelar arquivamento</Button></div>}
    </article>)}</div>}{query.hasNextPage&&<Button variant="outline" onClick={()=>void query.fetchNextPage()} disabled={query.isFetchingNextPage}>Carregar mais recorrências</Button>}
    </section>
  </div>;
}
