import { useRef,useState } from 'react';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Feedback } from '../../components/feedback';
import { useServices } from '../../hooks/use-services';
import { useAccounts,useFinanceMutation } from './hooks';
import { useSafeSpendSettings,useSafeSpend } from './safe-spend-hooks';
import { eligibleSafeAccounts,safeSpendWarnings } from './safe-spend-view';
import { formatMoney,parseMoney } from './money';
import { currencyDigits,SafeSpendSettingsInputSchema } from './contracts.generated';
import type { Account,Currency,SafeSpendSettings,SafeSpendSettingsInput,SafeSpendView } from './contracts.generated';
function Settings({currency,accounts,initial,onSaved,onCancel}:{currency:Currency;accounts:Account[];initial:SafeSpendSettings|null;onSaved:()=>void;onCancel:()=>void}) {
  const {finance}=useServices(),mutation=useFinanceMutation<SafeSpendSettingsInput>(i=>finance.putSafeSpendSettings(i)),locked=useRef(false),[error,setError]=useState(''),choices=eligibleSafeAccounts(accounts,currency);
  const digits=currencyDigits[currency],buffer=initial?String(BigInt(initial.safetyBufferMinor)/10n**BigInt(digits))+(digits?'.'+String(BigInt(initial.safetyBufferMinor)%10n**BigInt(digits)).padStart(digits,'0'):''):'0';
  return <section className="finance-panel safe-settings"><h2>Configurar dinheiro disponível</h2><p>Escolha suas contas, uma reserva e o que proteger no planejamento.</p>
    <form className="safe-settings-form" onSubmit={async e=>{e.preventDefault();if(locked.current)return;locked.current=true;const data=new FormData(e.currentTarget);setError('');try{const input=SafeSpendSettingsInputSchema.parse({currency,accountIds:data.getAll('accountIds').map(String),safetyBufferMinor:parseMoney(String(data.get('buffer')),currency,false),respectBudget:data.has('budget'),reserveRecurrences:data.has('recurrences'),reserveGoalPlans:data.has('goals')});await mutation.mutateAsync(input);onSaved();}catch{setError('Selecione ao menos uma conta elegível e informe uma reserva não negativa. Se o serviço estiver indisponível, tente novamente.');}finally{locked.current=false;}}}>
      <fieldset disabled={mutation.isPending} className="safe-settings-fields">
        <fieldset className="safe-settings-section"><legend><span className="safe-step" aria-hidden="true">1</span>Quais contas considerar?</legend><p id="safe-accounts-help">Selecione o dinheiro que pode ser usado. Poupança só entra se você selecionar; investimento, crédito e dívida não são elegíveis.</p>
          <div className="safe-account-options">{choices.map(a=><label className="safe-account-option" key={a.id}><input type="checkbox" name="accountIds" value={a.id} aria-label={a.name} aria-describedby="safe-accounts-help" defaultChecked={initial?.accountIds.includes(a.id)??false}/><span className="safe-account-name"><strong>{a.name}</strong><small className="safe-unselected">Não selecionada</small><small className="safe-selected">Conta selecionada</small></span><span className="safe-account-balance">{formatMoney(a.balanceMinor,currency)}</span></label>)}</div>
          {!choices.length&&<p>Nenhuma conta ativa elegível nesta moeda. Cadastre uma conta líquida em Contas.</p>}
        </fieldset>
        <fieldset className="safe-settings-section"><legend><span className="safe-step" aria-hidden="true">2</span>Reserva de segurança</legend>
          <div className="safe-buffer-field"><label htmlFor="safe-spend-buffer">Quanto deseja manter intocado? ({currency})</label><Input id="safe-spend-buffer" name="buffer" inputMode="decimal" defaultValue={buffer} required aria-describedby="safe-spend-buffer-help"/><span id="safe-spend-buffer-help" className="card-field-help">Esse valor é descontado do dinheiro disponível, sem movimentá-lo. Não é uma conta bancária.</span></div>
        </fieldset>
        <fieldset className="safe-settings-section"><legend><span className="safe-step" aria-hidden="true">3</span>Regras do planejamento</legend><p>Como calcular o dinheiro disponível?</p>
          <div className="safe-planning-options"><label className="safe-planning-option"><span><strong>Respeitar orçamento mensal</strong><small>Limita o valor ao orçamento restante.</small></span><input name="budget" type="checkbox" aria-label="Respeitar orçamento mensal" defaultChecked={initial?.respectBudget??true}/></label>
            <label className="safe-planning-option"><span><strong>Reservar recorrências planejadas</strong><small>Considera as despesas previstas nas recorrências.</small></span><input name="recurrences" type="checkbox" aria-label="Reservar recorrências planejadas" defaultChecked={initial?.reserveRecurrences??true}/></label>
            <label className="safe-planning-option"><span><strong>Reservar planos mensais de metas</strong><small>Protege as contribuições planejadas para suas metas.</small></span><input name="goals" type="checkbox" aria-label="Reservar planos mensais de metas" defaultChecked={initial?.reserveGoalPlans??true}/></label></div>
        </fieldset>
      </fieldset><div className="finance-actions safe-settings-actions">{initial&&<Button type="button" variant="outline" disabled={mutation.isPending} onClick={onCancel}>Cancelar edição</Button>}<Button type="submit" disabled={mutation.isPending||!choices.length} aria-busy={mutation.isPending}>Salvar configuração</Button></div><div className="safe-settings-feedback" aria-live="polite">{error&&<Feedback>{error}</Feedback>}</div>
    </form></section>;
}
const breakdown=[['Liquidez','liquidFundsMinor'],['Cartões','cardCommitmentsMinor'],['Dívidas','debtCommitmentsMinor'],['Despesas futuras confirmadas','futureConfirmedExpensesMinor'],['Recorrências planejadas','plannedRecurrenceReserveMinor'],['Planos mensais de metas','goalReserveMinor'],['Reserva de segurança','safetyBufferMinor'],['Capacidade de caixa','cashCapacityMinor']] as const;
const sourceLabels={CARD_INVOICE:'Fatura',DEBT_MINIMUM:'Mínimo de dívida',FUTURE_EXPENSE:'Despesa futura',RECURRENCE:'Recorrência',GOAL_PLAN:'Plano de meta',SAFETY_BUFFER:'Reserva',EXPECTED_INCOME:'Receita prevista'};
const certaintyLabels={CONFIRMED:'Confirmado',PLANNED:'Planejado',PROJECTED:'Projetado'};
export function SafeSpendResult({view:v}:{view:SafeSpendView}) {return <>
  <section className="finance-panel safe-spend-primary" aria-label="Estimativa principal"><p className="eyebrow">ESTIMATIVA CONSERVADORA · {v.currency}</p><h2>Disponível com segurança até o fim do mês</h2><p className="safe-spend-amount" data-testid="safe-spend-headline">{formatMoney(v.safeToSpendMinor,v.currency)}</p><p className="safe-spend-daily">{formatMoney(v.dailySafeToSpendMinor,v.currency)} / dia · {v.remainingDaysInclusive} dia(s) restantes</p><p>Período: {v.today} até {v.periodEndExclusive} (fim exclusivo) · {v.timeZone}</p>{v.status==='OVERCOMMITTED'&&<Feedback>Faltam {formatMoney(v.shortfallMinor,v.currency)} para cobrir as reservas e compromissos considerados.</Feedback>}<p>Estimativa de planejamento baseada nos dados cadastrados. Não é garantia de que todas as obrigações estejam registradas.</p></section>
  <section className="finance-panel"><h2>Como o valor foi calculado</h2><dl className="card-metrics">{breakdown.map(([label,key])=><div key={key}><dt>{label}</dt><dd>{formatMoney(v[key],v.currency)}</dd></div>)}<div><dt>Teto restante do orçamento</dt><dd>{v.budgetHeadroomMinor===null?'Não aplicado':formatMoney(v.budgetHeadroomMinor,v.currency)}</dd></div><div><dt>Safe to Spend final</dt><dd>{formatMoney(v.safeToSpendMinor,v.currency)}</dd></div></dl><p>Liquidez − obrigações − planos − reserva = capacidade de caixa. Orçamento é teto: não é subtraído novamente.</p>{v.budgetCapApplied&&BigInt(v.budgetHeadroomMinor!)<BigInt(v.cashCapacityMinor)&&<p>Seu caixa permitiria {formatMoney(v.cashCapacityMinor,v.currency)}, mas o orçamento possui {formatMoney(v.budgetHeadroomMinor!,v.currency)} restantes.</p>}{v.budgetOverrunMinor!=='0'&&<Feedback>Seu orçamento mensal já foi excedido em {formatMoney(v.budgetOverrunMinor,v.currency)}. Caixa existente não significa orçamento disponível.</Feedback>}</section>
  <section className="finance-panel"><h2>Se as receitas previstas entrarem</h2><p>Projetado, não confirmado: {formatMoney(v.safeToSpendWithExpectedIncomeMinor,v.currency)}.</p><p>Receitas previstas: {formatMoney(v.projectedIncomeMinor,v.currency)}. Não compõem a estimativa principal.</p></section>
  <section className="finance-panel"><details open><summary><h2>Fontes e reservas consideradas</h2></summary><ul className="finance-list">{v.items.map((i,index)=><li key={i.sourceType+':'+i.sourceId+':'+index}><strong>{sourceLabels[i.sourceType]} · {i.label} · {formatMoney(i.amountMinor,v.currency)}</strong><span>{certaintyLabels[i.certainty]} · {i.included?'Considerado':'Excluído da base'}{i.date&&' · '+i.date}</span><span>{i.reason}</span></li>)}</ul><h3>Contas selecionadas</h3><ul className="finance-list">{v.accounts.map(a=><li key={a.id}>{a.name} · {formatMoney(a.balanceMinor,v.currency)}</li>)}</ul></details></section>
  <section className="finance-panel"><h2>Avisos e limitações</h2><ul>{v.warnings.map(w=><li key={w}>{safeSpendWarnings[w]}</li>)}</ul><details><summary>Premissas do cálculo</summary><ul>{v.assumptions.map(a=><li key={a}>{a}</li>)}</ul></details></section>
  </>;}
export function SafeSpendPage() {
  const [currency,setCurrency]=useState<Currency>('BRL'),[editing,setEditing]=useState(false),settings=useSafeSpendSettings(currency),accounts=useAccounts(),view=useSafeSpend(currency,!!settings.data);
  return <div className="cards-page"><div className="page-intro"><p className="eyebrow">PLANEJAMENTO, NÃO GARANTIA</p><h1 tabIndex={-1}>Quanto posso gastar com segurança?</h1><p>Dinheiro atual menos compromissos e reservas até o fim deste mês. Sem IA, conversão de moedas ou movimentos automáticos.</p></div>
    <label className="card-field">Moeda do planejamento<select className="finance-select" value={currency} onChange={e=>{setCurrency(e.target.value as Currency);setEditing(false);}}>{Object.keys(currencyDigits).map(c=><option key={c}>{c}</option>)}</select><span className="card-field-help">Cada moeda possui configuração independente. Não há total global.</span></label>
    {settings.isPending||accounts.isPending?<section className="finance-panel" aria-busy="true"><p role="status">Carregando configuração…</p></section>:settings.isError||accounts.isError?<section className="finance-panel"><Feedback>Não foi possível carregar a configuração.</Feedback><Button onClick={()=>{void settings.refetch();void accounts.refetch();}}>Tentar novamente</Button></section>:<>
      {(!settings.data||editing)&&<Settings key={currency+':'+(settings.data?.updatedAt??'new')} currency={currency} accounts={accounts.data} initial={settings.data} onSaved={()=>setEditing(false)} onCancel={()=>setEditing(false)}/>}
      {settings.data&&<><div className="finance-actions"><Button variant="outline" onClick={()=>setEditing(true)}>Editar configuração</Button><Button variant="outline" onClick={()=>void view.refetch()} disabled={view.isFetching}>Atualizar cálculo</Button></div>{view.isPending?<section className="finance-panel" aria-busy="true"><p role="status">Calculando estimativa…</p></section>:view.isError?<section className="finance-panel"><Feedback>Estimativa indisponível. Revise as contas selecionadas ou tente novamente. Nenhum valor parcial será apresentado.</Feedback><Button onClick={()=>void view.refetch()}>Tentar novamente</Button></section>:<SafeSpendResult view={view.data}/>}</>}
    </>}
  </div>;
}
