import { currencyDigits,type Currency,type YieldRule,type YieldRuleInput } from './contracts.generated';
export function yieldCapInput(value:string|null|undefined,currency:Currency){if(value==null)return '';const digits=currencyDigits[currency],s=BigInt(value).toString().padStart(digits+1,'0');return digits?s.slice(0,-digits)+','+s.slice(-digits):s;}
export function percentToDecimal(value:string){const m=/^(0|[1-9]\d*)(?:[.,](\d{1,16}))?$/.exec(value.trim());if(!m)throw Error('Informe uma porcentagem válida.');const fraction=m[2]??'',digits=BigInt(m[1]!+fraction),places=fraction.length+2;const text=digits.toString().padStart(places+1,'0');return (text.slice(0,-places)+'.'+text.slice(-places)).replace(/0+$/,'').replace(/\.$/,'');}
export function decimalPercent(value:string){const m=/^(\d+)(?:\.(\d+))?$/.exec(value);if(!m)return '—';const f=m[2]??'',digits=BigInt(m[1]!+f)*100n,places=f.length,text=digits.toString().padStart(places+1,'0');return places?(text.slice(0,-places)+','+text.slice(-places)).replace(/0+$/,'').replace(/,$/,''):text;}
export function yieldRuleLabel(rule:Pick<YieldRule,'ruleType'|'benchmark'|'benchmarkPercentage'|'fixedRate'|'ratePeriod'>){return rule.ruleType==='ZERO'?'Sem rendimento':rule.ruleType==='SAVINGS_BR'?'Poupança':rule.ruleType==='BENCHMARK_PERCENTAGE'?decimalPercent(rule.benchmarkPercentage??'0')+'% '+rule.benchmark:decimalPercent(rule.fixedRate??'0')+'% '+(rule.ratePeriod==='MONTHLY'?'a.m.':'a.a.');}
export function addYieldDays(date:string,days:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
export function yieldRulePayload(values:{type:'ZERO'|'CDI'|'SELIC'|'FIXED_RATE'|'SAVINGS_BR';date:string;rate:string;period:'ANNUAL'|'MONTHLY';calendar:'CALENDAR_365'|'BUSINESS_252';tax:YieldRuleInput['taxTreatment'];delay:string;capMinor:string|null;taxDate:string}):YieldRuleInput{
 return {ruleType:values.type==='CDI'||values.type==='SELIC'?'BENCHMARK_PERCENTAGE':values.type,effectiveFrom:values.date,benchmark:values.type==='CDI'||values.type==='SELIC'?values.type:null,benchmarkPercentage:values.type==='CDI'||values.type==='SELIC'?percentToDecimal(values.rate):null,fixedRate:values.type==='FIXED_RATE'?percentToDecimal(values.rate):null,ratePeriod:values.type==='FIXED_RATE'?values.period:null,dayCountConvention:values.type==='SAVINGS_BR'?'MONTHLY_ANNIVERSARY':values.type==='CDI'||values.type==='SELIC'?'BUSINESS_252':values.type==='FIXED_RATE'?values.calendar:'CALENDAR_365',taxTreatment:values.type==='SAVINGS_BR'?'BR_SAVINGS_EXEMPT':values.type==='ZERO'?'NONE':values.tax,eligibilityDelayDays:Number(values.delay),eligibleBalanceCapMinor:values.capMinor,taxReferenceDate:values.taxDate||null};
}
