import { Input } from '../../components/ui/input';
import { useState,useRef } from 'react';
import { Dialog } from '../../components/ui/dialog';
import { Button } from '../../components/ui/button';
import { Feedback } from '../../components/feedback';
import { useServices } from '../../hooks/use-services';
import { useMe } from '../../profile/hooks';
import { useAccounts,useFinanceMutation } from './hooks';
import { useYieldBenchmarks,useYieldProfiles,useYieldEstimate,useYieldSummary } from './yield-hooks';
import { YieldEditor } from './yield-form';
import { addYieldDays,decimalPercent,percentToDecimal,yieldRuleLabel } from './yield-view';
import { formatMoney,parseMoney } from './money';
import { validCivilDate } from './recurrence-view';
import type { Account,YieldProfile,YieldEstimate,YieldComparison } from './contracts.generated';
function Result({data,label}:{data:YieldEstimate;label:string}){
 if(data.status==='UNAVAILABLE')return <p role="status">{label}: taxa indisponível no momento.</p>;
 const display=(v:string|null)=>formatMoney(v??'0',data.currency);
 return <section className="yield-result"><h3>{label}</h3><dl><div><dt>Principal elegível</dt><dd>{display(data.principalMinor)}</dd></div><div><dt>Rendimento bruto estimado</dt><dd>{display(data.grossYieldMinor)}</dd></div><div><dt>Impostos estimados</dt><dd>{display(data.estimatedTaxesMinor)} · IOF {display(data.estimatedIofMinor)} · IR {display(data.estimatedIrMinor)}{data.estimatedIrRate?' ('+decimalPercent(data.estimatedIrRate)+'%)':''}</dd></div><div><dt>Rendimento líquido estimado</dt><dd>{display(data.estimatedNetYieldMinor)}</dd></div><div><dt>Valor final estimado</dt><dd>{display(data.estimatedNetValueMinor)}</dd></div></dl>
 {data.projection&&<p>Considerando a taxa atual constante. Projeção, não garantia.</p>}{data.calendarAssumption==='WEEKDAYS_ONLY'&&<p>Calendário futuro: segunda a sexta, sem feriados completos.</p>}{data.sourceStatus==='STALE'&&<p role="status">Usando o último dado disponível.</p>}{data.benchmarkSource&&<p>Fonte: Banco Central do Brasil · Observação {data.benchmarkAsOf??'indisponível'}</p>}{data.nextAnniversary&&<p>Rendimento creditado no aniversário. Próximo aniversário estimado: {data.nextAnniversary}.</p>}
 </section>;
}
function YieldAccount({account,profile,today,onEdit}:{account:Account;profile:YieldProfile;today:string;onEdit:()=>void}){
 const {finance}=useServices(),[horizon,setHorizon]=useState('30'),[custom,setCustom]=useState(addYieldDays(today,90)),[historical,setHistorical]=useState(false),[historyFrom,setHistoryFrom]=useState(profile.rules[0]?.effectiveFrom??today),[archiveConfirm,setArchiveConfirm]=useState(false);
 const enabled=account.isActive&&profile.status==='ACTIVE',to=horizon==='custom'?custom:addYieldDays(today,Number(horizon)),valid=validCivilDate(to)&&to>today;
 const estimate=useYieldEstimate(account.id,{from:today,to,assumption:'CURRENT_RATE'},enabled&&valid),annual=useYieldEstimate(account.id,{from:today,to:addYieldDays(today,365),assumption:'CURRENT_RATE'},enabled),history=useYieldEstimate(account.id,{from:historyFrom,to:today},historical&&validCivilDate(historyFrom)&&historyFrom<today);
 const archive=useFinanceMutation<string>(id=>finance.archiveYield(id)),rule=profile.rules.find(r=>r.effectiveFrom<=today&&(!r.effectiveTo||r.effectiveTo>today));
 return <section className="finance-panel"><h2>{account.name} · {account.currency}</h2><p>Saldo real atual: <strong>{formatMoney(account.balanceMinor,account.currency)}</strong></p><p>{rule?yieldRuleLabel(rule):'Regra ainda não iniciada'} · {profile.status==='ARCHIVED'?'Arquivado':account.isActive?'Ativo':'Conta inativa'}</p><p>Estimativa — não altera seu saldo.</p>
 {enabled?<><label>Prazo da projeção — {account.name}<select className="finance-select" value={horizon} onChange={e=>setHorizon(e.target.value)}><option value="30">30 dias</option><option value="90">90 dias</option><option value="365">1 ano (365 dias)</option><option value="custom">Personalizado</option></select></label>{horizon==='custom'&&<label>Fim da projeção — {account.name}<Input calendarLabel={"Fim da projeção — " + account.name} className="finance-select" type="date" value={custom} onChange={e=>setCustom(e.target.value)}/></label>}
 {estimate.isPending?<p role="status">Calculando projeção…</p>:estimate.isError?<Feedback><p>Não foi possível calcular a projeção. Confira o prazo (máximo 10 anos).</p><Button variant="outline" onClick={()=>void estimate.refetch()}>Tentar novamente</Button></Feedback>:estimate.data?<Result data={estimate.data} label={'Projeção — '+(horizon==='custom'?to:horizon+' dias')}/>:null}
 {annual.data&&<Result data={annual.data} label="Estimativa de 12 meses (365 dias)"/>}<div className="finance-actions"><Button variant="outline" onClick={onEdit}>Nova versão — {account.name}</Button><Button variant="outline" onClick={()=>setArchiveConfirm(true)}>Arquivar rendimento — {account.name}</Button></div></>:<p>Projeções futuras desabilitadas; histórico preservado.</p>}
 {archiveConfirm&&<Dialog role="alertdialog" title="Arquivar rendimento" onClose={() => setArchiveConfirm(false)} pending={archive.isPending}><p>Arquivar preserva o histórico e é definitivo.</p>{archive.isError&&<Feedback>{(archive.error as Error).message}</Feedback>}<Button variant="destructive" disabled={archive.isPending} onClick={async()=>{try{await archive.mutateAsync(account.id);setArchiveConfirm(false);}catch{/* Feedback above. */}}}>Confirmar arquivamento</Button><Button variant="outline" disabled={archive.isPending} onClick={()=>setArchiveConfirm(false)}>Cancelar arquivamento</Button></Dialog>}
 <details><summary>Histórico de regras — {account.name}</summary><ul className="finance-list">{profile.rules.map(r=><li key={r.id}><span>{r.effectiveFrom} → {r.effectiveTo??'em aberto'} (fim exclusivo)</span><strong>{yieldRuleLabel(r)}</strong><p>Carência: {r.eligibilityDelayDays} dias · Limite: {r.eligibleBalanceCapMinor===null?'sem limite':formatMoney(r.eligibleBalanceCapMinor,account.currency)}</p></li>)}</ul></details>
 <div className="finance-actions"><Button variant="outline" onClick={()=>setHistorical(v=>!v)}>Histórico estimado — {account.name}</Button></div>{historical&&<div><p>Histórico estimado, não confirmado. Usa saldos reais elegíveis e simula a composição das taxas diárias; a poupança usa o menor saldo real do período. Não reinveste ganhos nas contas nem equivale ao rendimento pago pelo banco.</p><label>Início do histórico — {account.name}<Input calendarLabel={"Início do histórico — " + account.name} className="finance-select" type="date" value={historyFrom} max={addYieldDays(today,-1)} onChange={e=>setHistoryFrom(e.target.value)}/></label>{history.isPending?<p role="status">Calculando histórico…</p>:history.isError?<Feedback><p>Histórico indisponível. Use intervalo de até 10 anos.</p><Button variant="outline" onClick={()=>void history.refetch()}>Tentar novamente</Button></Feedback>:history.data?<><Result data={history.data} label="Rendimento histórico estimado"/><div className="net-worth-table" role="region" aria-label="Tabela financeira" tabIndex={0}><table><caption>Créditos estimados; poupança somente no aniversário</caption><thead><tr><th scope="col">Data</th><th scope="col">Rendimento bruto acumulado</th></tr></thead><tbody>{history.data.points.map(p=><tr key={p.date}><th scope="row">{p.date}</th><td>{formatMoney(p.grossYieldMinor,account.currency)}</td></tr>)}</tbody></table></div></>:null}</div>}
 </section>;
}
function Comparison({today}:{today:string}){
 const {finance}=useServices(),[principal,setPrincipal]=useState('1000'),[rate,setRate]=useState('10'),[period,setPeriod]=useState<'ANNUAL'|'MONTHLY'>('ANNUAL'),[to,setTo]=useState(addYieldDays(today,365)),[tax,setTax]=useState<'NONE'|'BR_FIXED_INCOME_STANDARD'>('NONE'),[data,setData]=useState<YieldComparison|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),lock=useRef(false);
 return <section className="finance-panel"><h2>Comparar regras · BRL</h2><p>100% CDI × poupança × taxa fixa. Mesmo principal e prazo, sem criar contas.</p><form className="recurrence-form" onSubmit={async e=>{e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');setData(null);try{if(!validCivilDate(to)||to<=today)throw Error('Informe um prazo futuro válido.');setData(await finance.yieldComparison({currency:'BRL',principalMinor:parseMoney(principal,'BRL'),from:today,to,fixedRate:percentToDecimal(rate),ratePeriod:period,taxTreatment:tax}));}catch(err){setError((err as Error).message);}finally{lock.current=false;setBusy(false);}}}>
 <label>Principal da comparação<input className="finance-select" inputMode="decimal" value={principal} onChange={e=>setPrincipal(e.target.value)}/></label><label>Taxa fixa da comparação (%)<input className="finance-select" inputMode="decimal" value={rate} onChange={e=>setRate(e.target.value)}/></label><label>Período da comparação<select className="finance-select" value={period} onChange={e=>setPeriod(e.target.value as typeof period)}><option value="ANNUAL">Anual</option><option value="MONTHLY">Mensal</option></select></label><label>Fim da comparação<Input calendarLabel="Fim da comparação" className="finance-select" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Impostos da comparação<select className="finance-select" value={tax} onChange={e=>setTax(e.target.value as typeof tax)}><option value="NONE">Sem cálculo tributário</option><option value="BR_FIXED_INCOME_STANDARD">IR/IOF estimados · CDI e fixa</option></select></label><div className="ui-form-actions"><Button type="submit" disabled={busy}>{busy?'Comparando…':'Comparar rendimentos'}</Button></div>
 </form>{error&&<Feedback>{error}</Feedback>}{data&&<div className="net-worth-metrics"><Result data={data.cdi} label="100% CDI"/><Result data={data.savings} label="Poupança"/><Result data={data.fixed} label="Taxa fixa"/></div>}</section>;
}
export function YieldPage(){
 const me=useMe(),timezone=me.data?.profile?.timezone??'UTC',today=new Intl.DateTimeFormat('en-CA',{timeZone:timezone}).format(new Date()),accounts=useAccounts(),profiles=useYieldProfiles(),benchmarks=useYieldBenchmarks(),summary=useYieldSummary({from:today,to:addYieldDays(today,30)}),[editor,setEditor]=useState<{profile:YieldProfile|null}|null>(null);
 const available=(accounts.data??[]).filter(a=>a.isActive&&!profiles.data?.some(p=>p.accountId===a.id));
 return <div className="yield-page"><div className="page-intro"><h1 tabIndex={-1}>Rendimentos</h1><p>Estimativa — não altera seu saldo, transações ou patrimônio real. Sem câmbio ou regra específica de banco.</p></div>
 <section aria-label="Benchmarks oficiais"><h2>Taxas de referência</h2>{benchmarks.isPending?<p role="status">Carregando taxas…</p>:benchmarks.isError?<Feedback><p>Não foi possível carregar as taxas.</p><Button variant="outline" onClick={()=>void benchmarks.refetch()}>Tentar novamente</Button></Feedback>:<div className="net-worth-metrics">{benchmarks.data.map(b=><section className="finance-panel" key={b.benchmark}><h3>{b.benchmark==='SELIC_TARGET'?'Meta Selic':b.benchmark==='SELIC'?'Selic Over':b.benchmark}</h3><strong>{b.value===null?'Taxa indisponível no momento.':decimalPercent(b.value)+'% '+(b.unit==='MONTHLY_DECIMAL'?'no período mensal':'a.a.')}</strong><p>Banco Central do Brasil · SGS {b.seriesCode}</p><p>Observação: {b.observedDate??'indisponível'}</p><p>Atualizado em: {b.lastUpdatedAt?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:timezone}).format(new Date(b.lastUpdatedAt)):'indisponível'}</p><p role="status">{b.sourceStatus==='CURRENT'?'Atualizado':b.sourceStatus==='STALE'?'Usando o último dado disponível.':'Taxa indisponível no momento.'}</p></section>)}</div>}</section>
 <section className="finance-panel"><h2>Estimativa consolidada · 30 dias</h2><p>Moedas separadas; valores indisponíveis não são somados como estimativas válidas.</p>{summary.isPending?<p role="status">Calculando resumo…</p>:summary.isError?<Feedback><p>Não foi possível calcular o resumo.</p><Button variant="outline" onClick={()=>void summary.refetch()}>Tentar novamente</Button></Feedback>:<ul className="finance-list">{summary.data.totals.map(t=><li key={t.currency}><h3>{t.currency} · {t.yieldingAccounts} conta(s)</h3><p>Principal: {formatMoney(t.principalMinor,t.currency)} · Bruto estimado: {formatMoney(t.estimatedGrossYieldMinor,t.currency)} · Líquido estimado: {formatMoney(t.estimatedNetYieldMinor,t.currency)}</p>{t.unavailableAccounts>0&&<p>{t.unavailableAccounts} estimativa(s) indisponível(is).</p>}</li>)}</ul>}</section>
 <div className="finance-actions"><Button disabled={!available.length||profiles.isPending} onClick={()=>setEditor({profile:null})}>Configurar rendimento</Button></div>
 {accounts.isPending||profiles.isPending?<p role="status">Carregando contas com rendimento…</p>:accounts.isError||profiles.isError?<Feedback><p>Não foi possível carregar as contas.</p><Button variant="outline" onClick={()=>{void accounts.refetch();void profiles.refetch();}}>Tentar novamente</Button></Feedback>:profiles.data.length===0?<section className="finance-panel"><h2>Nenhum rendimento configurado</h2><p>Configure explicitamente uma conta ativa. O tipo da conta não ativa rendimentos automaticamente.</p></section>:profiles.data.map(p=>{const a=accounts.data.find(a=>a.id===p.accountId);return a?<YieldAccount key={p.id} account={a} profile={p} today={today} onEdit={()=>setEditor({profile:p})}/>:null;})}
 {editor&&<YieldEditor key={editor.profile?.id??'new'} accounts={editor.profile?(accounts.data??[]).filter(a=>a.id===editor.profile!.accountId):available} profile={editor.profile} today={today} onClose={()=>setEditor(null)}/>}
 <Comparison today={today}/><p>Estimativa de impostos, não imposto exato a pagar. Sem lotes da instituição. Nenhum movimento financeiro é criado pelo motor.</p>
 </div>;
}
