import { describe,it,expect } from 'vitest';
import { civilDateLabel,validCivilDate,recurrencePeriod } from '../../src/features/finance/recurrence-view';
import { RecurrenceInputSchema,RecurrencePatchSchema,FinancialCalendarSchema,SubscriptionRadarSchema } from '../../src/features/finance/contracts.generated';
import { recurrenceFixture,entryFixture,calendarFixture,radarFixture } from '../fixtures/recurrences';
describe('recurrence presentation and generated boundary',()=>{
  it.each(['2026-10-31','2026-11-30','2026-12-31','2027-01-31','2000-02-29'])('keeps civil date %s unchanged by timezone',value=>{const [year,month,day]=value.split('-');expect(civilDateLabel(value,'pt-BR')).toBe(`${day}/${month}/${year}`);expect(civilDateLabel(value,'en-US')).toBe(`${month}/${day}/${year}`);});
  it.each(['2026-02-29','1900-02-29','2026-04-31','9999-01-01','2026-1-01','2026-10-02T00:00:00Z'])('rejects invalid form date %s',value=>{expect(validCivilDate(value)).toBe(false);});
  it('shows absent next date and explicit interval units',()=>{expect(civilDateLabel(null)).toBe('Sem próxima ocorrência');expect(recurrencePeriod({frequency:'WEEKLY',intervalCount:2})).toBe('A cada 2 semanas');expect(recurrencePeriod({frequency:'MONTHLY',intervalCount:3})).toBe('A cada 3 meses');expect(recurrencePeriod({frequency:'YEARLY',intervalCount:1})).toBe('Anual');});
  it('rejects owner/derived input and edits to fixed type/currency',()=>{const r=recurrenceFixture();const input={name:r.name,transactionType:r.transactionType,recurrenceKind:r.recurrenceKind,amountMinor:r.amountMinor,currency:r.currency,frequency:r.frequency,intervalCount:r.intervalCount,startDate:r.startDate};expect(RecurrenceInputSchema.safeParse(input).success).toBe(true);for(const field of ['auth_user_id','owner','nextOccurrenceDate','status'])expect(RecurrenceInputSchema.safeParse({...input,[field]:r.id}).success).toBe(false);expect(RecurrencePatchSchema.safeParse({currency:'USD'}).success).toBe(false);expect(RecurrencePatchSchema.safeParse({transactionType:'INCOME'}).success).toBe(false);});
  it('accepts exact signed projection totals and actual multiple radar occurrences',()=>{const row=recurrenceFixture({amountMinor:'9223372036854775807',frequency:'WEEKLY'}),entries=['2026-10-02','2026-10-09','2026-10-16','2026-10-23','2026-10-30'].map(date=>entryFixture(row,date));const calendar=FinancialCalendarSchema.parse(calendarFixture(entries));expect(calendar.totals[0]?.projectedNetMinor).toBe('-46116860184273879035');const radar=SubscriptionRadarSchema.parse(radarFixture([row],entries));expect(radar.totals[0]).toMatchObject({occurrenceCount:5,amountMinor:'46116860184273879035'});});
});
