import { z } from 'zod';
export const emailSchema = z.object({ email: z.email('Informe um e-mail válido.').max(254).trim() });
export const recoveryEmailSchema = z.object({ email: z.string().trim().toLowerCase().pipe(z.email('Informe um e-mail válido.').max(254)) });
export const loginSchema = emailSchema.extend({ password: z.string().min(1, 'Informe sua senha.').max(128, 'Use até 128 caracteres.') });
const password = z.string().min(8, 'Use pelo menos 8 caracteres.').max(128, 'Use até 128 caracteres.');
export const passwordSchema = z.object({ password, confirmPassword: z.string() }).refine((data) => data.password === data.confirmPassword, { path: ['confirmPassword'], message: 'As senhas precisam ser iguais.' });
export const signupSchema = emailSchema.extend({ password, confirmPassword: z.string() }).refine((data) => data.password === data.confirmPassword, { path: ['confirmPassword'], message: 'As senhas precisam ser iguais.' });
export type LoginInput = z.infer<typeof loginSchema>;
export type SignupInput = z.infer<typeof signupSchema>;
export type PasswordInput = z.infer<typeof passwordSchema>;
export type EmailInput = z.infer<typeof emailSchema>;
export type RecoveryEmailInput = z.infer<typeof recoveryEmailSchema>;
